export const localization = {
    quickstart_osc: { en: "Make sure to enable OSC!", jp: "OSCを有効にしてください！", cn: "请确认OSC已开启！", kr: "OSC를 활성화하세요!", tr: "OSC ayarını etkinleştirdiğinizden emin olun!" },
    windows_mic_settings: { en: "Check your Windows default microphone settings!", jp: "Windowsのデフォルトマイクの設定を確認してください！", cn: "请检查windows初始麦克风设定！", kr: "Windows 기본 마이크 설정을 확인하세요!", tr: "Varsayılan mikrofon ayarlarınızı kontrol edin!" },
    windows_mic_details: { en: "Make sure to check your Windows microphone settings. Your VR headset microphone (or your actual microphone) must be selected. Don't forget to restart Kikitan after changing the default microphone!", jp: "Windowsのマイク設定を確認してください。VRヘッドセットのマイク（または実際に使用しているマイク）が選択されている必要があります。マイクを変更した後にキキタンの再起動が必要です。", cn: "请确认windows麦克风设定。请选定VR设备的麦克风（或实际正在使用的麦克风）。在更改麦克风后设置请不要忘了重启Kikitan", kr: "Windows 마이크 설정을 확인하세요. VR 헤드셋 마이크(또는 실제 마이크)를 선택해야 합니다. 기본 마이크를 변경한 후 Kikitan을 재시작하는 것을 잊지 마세요!", tr: "Windows varsayılan mikrofon ayarlarınızı kontrol edin. VR başlık mikrofonunuz (veya gerçek mikrofonunuz) seçili olmalıdır. Varsayılan mikrofonu değiştirdikten sonra Kikitan'ı yeniden başlatmayı unutmayın!" },
    open_win_audio: { en: "Open Windows Audio Settings", jp: "Windowsのオーディオ設定を開く", cn: "打开windows音频设置", kr: "Windows 오디오 설정 열기", tr: "Windows Ses Ayarlarını Aç" },
    stt_text: { en: "[VR ONLY] How to use SteamVR STT (Speech to Text)", jp: "[VRのみ] SteamVR STT (音声からテキストへ) の使用方法", cn: "［仅限VR］SteamVR STT(语音输入）的使用方法", kr: "[VR 전용] SteamVR STT (음성 인식) 사용 방법", tr: "[SADECE VR] SteamVR STT (Sesli Yazma) nasıl kullanılır" },
    mode_selection: { en: "Mode Selection", jp: "モードの選択", cn: "模式选择", kr: "모드 선택", tr: "Mod Seçimi" },
    mode_selection_details: { en: "You can change the mode from here. Translation sends both what is said and its translation to VRChat. With transcription, only what is said is sent to VRChat.", jp: "ここからモードを変更できます。 翻訳では、発言内容とその翻訳の両方が VRChat に送信されます。 文字起こしでは、話した内容のみが VRChat に送信されます。", cn: "您可以在这里更换模式。此翻译将会发送输入内容和翻译之后的内容至VRChat。通过转录，只有说出的内容会被输送至VRChat。", kr: "여기서 모드를 변경할 수 있습니다. 번역 모드에서는 말한 내용과 번역된 내용이 모두 VRChat에 전송됩니다. 전사 모드에서는 말한 내용만 VRChat에 전송됩니다.", tr: "Modu buradan değiştirebilirsiniz. Çeviri, söylenen şeyi ve çevirisini VRChat'e gönderir. Transkripsiyonda sadece söylenen şey VRChat'e gönderilir." },
    thank_you: { en: "Thank you for using Kikitan!", jp: "Kikitanをご利用いただき、ありがとうございます！", cn: "感谢使用Kikitan!", kr: "Kikitan을 사용해 주셔서 감사합니다!", tr: "Kikitan'ı kullandığın için teşekkür ederim!" },
    thank_you_details: { en: "Kikitan is an open source project! Any support for this project would be appreciated!", jp: "キキタンはオープンソースプロジェクトです！このプロジェクトへのどんな支援も感謝します！", cn: "Kikitan 是一个开源项目！感谢所有对此项目的帮助！", kr: "Kikitan은 오픈 소스 프로젝트입니다! 이 프로젝트에 대한 지원에 감사드립니다!", tr: "Kikitan açık kaynak bir projedir! Projeye yapılan her türlü desteğe minnettarım!" },
    next: { en: "Next", jp: "次", cn: "下一页", kr: "다음", tr: "İleri" },
    previous: { en: "Previous", jp: "前", cn: "上一页", kr: "이전", tr: "Geri" },
    open_repo: { en: "Open Repository", jp: "リポジトリを開く", cn: "打开项目库", kr: "저장소 열기", tr: "Depoyu Aç" },
    close_menu: { en: "Close Menu", jp: "メニューを閉じる", cn: "关闭菜单", kr: "메뉴 닫기", tr: "Menüyü Kapat" },
    translation: { en: "Translation", jp: "翻訳", cn: "翻译", kr: "번역", tr: "Çeviri" },
    transcription: { en: "Transcription", jp: "文字起こし", cn: "转录", kr: "전사", tr: "Transkripsiyon" },
    translation_disabled: { en: "Translation is disabled. Enable translation from the setting above.", jp: "翻訳が無効になっています。上記の設定から翻訳を有効にしてください。", cn: "翻译已禁用。请从上面的设置中启用翻译。", kr: "번역이 비활성화되었습니다. 위 설정에서 번역을 활성화하세요.", tr: "Çeviri devre dışı. Yukarıdaki ayarları kullanarak çeviriyi etkinleştirin." },
    steamvr_connection: { en: "SteamVR Connection", jp: "SteamVR 接続", cn: "SteamVR 连接", kr: "SteamVR 연결", tr: "SteamVR Bağlantısı" },
    language_settings: { en: "Language Settings", jp: "言語設定", cn: "语言设置", kr: "언어 설정", tr: "Dil Ayarları" },
    vrchat_settings: { en: "VRChat Settings", jp: "VRChat 設定", cn: "VRChat 设置", kr: "VRChat 설정", tr: "VRChat Ayarları" },
    omit_questionmark: { en: "Omit the trailing question mark", jp: "文末の疑問符を省略", cn: "请省略句尾的问号", kr: "문장의 끝에 물음표를 생략하세요", tr: "Soru işaretini kaldır" },
    translation_first: { en: "Translation first", jp: "最初に翻訳文を表示", cn: "先显示翻译结果", kr: "먼저 번역 결과 표시", tr: "Önce çeviriyi göster" },
    send_typing_while_talking: { en: "Send typing status while talking", jp: "会話中に入力ステータスを送信する", cn: "正在说话时发送“正在输入”的状态", kr: "말하는 동안 입력 상태 보내기", tr: "Konuşurken yazma durumu gönder" },
    chatbox_update_speed: { en: "Chatbox update speed", jp: "チャットボックス更新速度", cn: "聊天框更新速度", kr: "채팅창 업데이트 속도", tr: "Sohbet kutusu güncelleme hızı" },
    slow: { en: "Slow", jp: "遅い", cn: "慢", kr: "느림", tr: "Yavaş" },
    medium: { en: "Medium", jp: "中", cn: "中", kr: "중간", tr: "Orta" },
    fast: { en: "Fast", jp: "速い", cn: "快", kr: "빠름", tr: "Hızlı" },
    osc_address: { en: "OSC Address", jp: "OSC アドレス", cn: "OSC 地址", kr: "OSC 주소", tr: "OSC Adresi" },
    osc_port: { en: "OSC Port", jp: "OSC ポート", cn: "OSC 端口", kr: "OSC 포트", tr: "OSC Portu" },
    dont_send_when_muted: { en: "Don't send chatbox messages when muted (Only translation mode)", jp: "ミュート時にチャットボックスメッセージを送信しない（翻訳モードのみ）", cn: "静音时不发送聊天框消息（仅限翻译模式）", kr: "음소거 상태에서 채팅박스 메시지를 보내지 않음 (번역 모드 전용)", tr: "Sessizken sohbet kutusu mesajları gönderme (Sadece çeviri modu)" },
    changelogs: { en: "Changelogs", jp: "変更履歴", cn: "更新日志", kr: "변경 사항", tr: "Değişiklikler" },
    english_gender_text: { en: "When translating to English, change the pronoun. (Ex. He is a doctor/She is a doctor). Useful for languages with gender neutral structure.", jp: "変更履歴", cn: "翻译成英语时，请更改代词。（例如：他是医生/她是医生。）这对于性别中立结构的语言很有用。", kr: "영어로 번역할 때, 대명사를 변경하세요. (예: 그는 의사입니다/그녀는 의사입니다.) 성 중립적 구조를 가진 언어에 유용합니다", tr: "İngilizceye çevirirken, zamiri değiştirin. (Ör. O bir doktordur. \"O\" burada kız veya erkek olabilir) Cinsiyet nötr yapıya sahip diller için faydalıdır." },
    gender: { en: "Gender", jp: "性別", cn: "性别", kr: "성별", tr: "Cinsiyet" },
};