export const localization = {
    quickstart_osc: {
        en: "Make sure to enable OSC!",
        jp: "OSCを有効にしてください！",
        cn: "请确认OSC已开启！",
        kr: "OSC를 활성화하세요!",
        tr: "OSC ayarını etkinleştirdiğinizden emin olun!",
    },
    how_to_setup_and_use_kikitan: {
        en: "How to setup and use Kikitan",
        jp: "Kikitanの設定と使用方法",
        cn: "如何设置和使用Kikitan",
        kr: "Kikitan 설정 및 사용 방법",
        tr: "Kikitan'ı nasıl kurup kullanabilirsiniz",
    },
    windows_mic_settings: {
        en: "Check your Windows default microphone settings!",
        jp: "Windowsのデフォルトマイクの設定を確認してください！",
        cn: "请检查windows初始麦克风设定！",
        kr: "Windows 기본 마이크 설정을 확인하세요!",
        tr: "Varsayılan mikrofon ayarlarınızı kontrol edin!",
    },
    windows_mic_details: {
        en: "Make sure to check your Windows microphone settings. Your VR headset microphone (or your actual microphone) must be selected. Don't forget to restart Kikitan after changing the default microphone!",
        jp: "Windowsのマイク設定を確認してください。VRヘッドセットのマイク（または実際に使用しているマイク）が選択されている必要があります。マイクを変更した後にキキタンの再起動が必要です。",
        cn: "请确认windows麦克风设定。请选定VR设备的麦克风（或实际正在使用的麦克风）。在更改麦克风后设置请不要忘了重启Kikitan",
        kr: "Windows 마이크 설정을 확인하세요. VR 헤드셋 마이크(또는 실제 마이크)를 선택해야 합니다. 기본 마이크를 변경한 후 Kikitan을 재시작하는 것을 잊지 마세요!",
        tr: "Windows varsayılan mikrofon ayarlarınızı kontrol edin. VR başlık mikrofonunuz (veya gerçek mikrofonunuz) seçili olmalıdır. Varsayılan mikrofonu değiştirdikten sonra Kikitan'ı yeniden başlatmayı unutmayın!",
    },
    announcement: {
        en: "Announcement",
        jp: "お知らせ",
        cn: "公告",
        kr: "공지",
        tr: "Duyuru",
    },
    enable_gemini: {
        en: "Enable Gemini",
        jp: "ジェミニを有効にする",
        cn: "启用Gemini",
        kr: "젬니 활성화",
        tr: "Gemini'yi etkinleştir",
    },
    enable_gemini_microphone_capture: {
        en: "Enable Gemini Microphone Capture (Disabling will use WebSpeech instead)",
        jp: "ジェミニのマイクキャプチャを有効にする（無効にするとWebSpeechが使用されます）",
        cn: "启用Gemini麦克风捕获（禁用后将改用WebSpeech）",
        kr: "젬니 마이크 캡처 활성화 (비활성화하면 대신 WebSpeech 사용)",
        tr: "Gemini Mikrofon Yakalamayı Etkinleştir (Devre dışı bırakılırsa WebSpeech kullanılır)",
    },
    enable_desktop_capture: {
        en: "Enable Desktop Capture",
        jp: "デスクトップキャプチャを有効にする",
        cn: "启用桌面捕获",
        kr: "데스크톱 캡처 활성화",
        tr: "Masaüstü Yakalama'yı Etkinleştir",
    },
    disable_desktop_capture: {
        en: "Disable Desktop Capture",
        jp: "デスクトップキャプチャを無効にする",
        cn: "禁用桌面捕获",
        kr: "데스크톱 캡처 비활성화",
        tr: "Masaüstü Yakalama'yı Devre Dışı Bırak",
    },
    open_win_audio: {
        en: "Open Windows Audio Settings",
        jp: "Windowsのオーディオ設定を開く",
        cn: "打开windows音频设置",
        kr: "Windows 오디오 설정 열기",
        tr: "Windows Ses Ayarlarını Aç",
    },
    stt_text: {
        en: "[VR ONLY] How to use SteamVR STT (Speech to Text)",
        jp: "[VRのみ] SteamVR STT (音声からテキストへ) の使用方法",
        cn: "［仅限VR］SteamVR STT(语音输入）的使用方法",
        kr: "[VR 전용] SteamVR STT (음성 인식) 사용 방법",
        tr: "[SADECE VR] SteamVR STT (Sesli Yazma) nasıl kullanılır",
    },
    change_basic_settings: {
        en: "Change basic settings",
        jp: "基本設定を変更する",
        cn: "更改基本设置",
        kr: "기본 설정 변경",
        tr: "Temel ayarları değiştir",
    },
    text: {
        en: "Text",
        jp: "テキスト",
        cn: "文本",
        kr: "텍스트",
        tr: "Metin",
    },
    mode_selection: {
        en: "Mode Selection",
        jp: "モードの選択",
        cn: "模式选择",
        kr: "모드 선택",
        tr: "Mod Seçimi",
    },
    mode_selection_details: {
        en: "You can change the mode from here. Translation translates your speech to the specified language while STT only converts your speech to text without translation (can be used if you don't want to speak in game but also don't want to type in the chatbox).",
        jp: "ここからモードを変更できます。翻訳はあなたの音声を指定された言語に翻訳しますが、STTは翻訳せずに音声をテキストに変換するだけです（ゲーム内で話したくないがチャットボックスに入力したくない場合に使用できます）。",
        cn: "您可以从这里更改模式。翻译会将您的语音翻译成指定的语言，而STT只会将您的语音转换为文本而不进行翻译（如果您不想在游戏中说话但也不想在聊天框中输入，可以使用此功能）。",
        kr: "여기에서 모드를 변경할 수 있습니다. 번역은 사용자의 음성을 지정된 언어로 번역하는 반면 STT는 번역 없이 음성을 텍스트로 변환합니다(게임에서 말하고 싶지 않지만 채팅창에 입력하고 싶지 않은 경우 사용할 수 있음).",
        tr: "Buradan modu değiştirebilirsiniz. Çeviri, konuşmanızı belirtilen dile çevirirken, STT yalnızca konuşmanızı çeviri olmadan metne dönüştürür (oyunda konuşmak istemiyorsanız ancak sohbet kutusuna yazmak da istemiyorsanız kullanılabilir).",
    },
    thank_you: {
        en: "Thank you for using Kikitan!",
        jp: "Kikitanをご利用いただき、ありがとうございます！",
        cn: "感谢使用Kikitan!",
        kr: "Kikitan을 사용해 주셔서 감사합니다!",
        tr: "Kikitan'ı kullandığın için teşekkür ederim!",
    },
    thank_you_details: {
        en: "Kikitan will always be free and open source! If you want to support the project, you can do so from Buy Me a Coffee or through Booth.pm!",
        jp: "Kikitanは常に無料でオープンソースです！プロジェクトをサポートしたい場合は、Buy Me a CoffeeまたはBooth.pmからサポートできます！",
        cn: "Kikitan将永远是免费和开源的！如果您想支持该项目，可以通过Buy Me a Coffee或Booth.pm进行支持！",
        kr: "Kikitan은 항상 무료이며 오픈 소스입니다! 프로젝트를 지원하고 싶다면 Buy Me a Coffee 또는 Booth.pm을 통해 지원할 수 있습니다!",
        tr: "Kikitan her zaman ücretsiz ve açık kaynaklı olacaktır! Projeyi desteklemek isterseniz, Buy me a Coffee veya Booth.pm üzerinden destekleyebilirsiniz!",
    },
    next: { en: "Next", jp: "次", cn: "下一页", kr: "다음", tr: "İleri" },
    previous: {
        en: "Previous",
        jp: "前",
        cn: "上一页",
        kr: "이전",
        tr: "Geri",
    },
    open_repo: {
        en: "Open Repository",
        jp: "リポジトリを開く",
        cn: "打开项目库",
        kr: "저장소 열기",
        tr: "Depoyu Aç",
    },
    close_menu: {
        en: "Close Menu",
        jp: "メニューを閉じる",
        cn: "关闭菜单",
        kr: "메뉴 닫기",
        tr: "Menüyü Kapat",
    },
    translation: {
        en: "Translation",
        jp: "翻訳",
        cn: "翻译",
        kr: "번역",
        tr: "Çeviri",
    },
    type_here: {
        en: "Type here...",
        jp: "ここに入力...",
        cn: "在这里输入...",
        kr: "여기에 입력...",
        tr: "Buraya yazın...",
    },
    stt_only: {
        en: "Speech-to-Text (STT) Only",
        jp: "音声からテキストへ (STT) のみ",
        cn: "仅语音转文本 (STT)",
        kr: "음성 인식 전용 (STT)",
        tr: "Sadece Sesli Metin (STT)",
    },
    translation_disabled: {
        en: "Translation is disabled. Enable translation from the setting above.",
        jp: "翻訳が無効になっています。上記の設定から翻訳を有効にしてください。",
        cn: "翻译已禁用。请从上面的设置中启用翻译。",
        kr: "번역이 비활성화되었습니다. 위 설정에서 번역을 활성화하세요.",
        tr: "Çeviri devre dışı. Yukarıdaki ayarları kullanarak çeviriyi etkinleştirin.",
    },
    language_settings: {
        en: "Language Settings",
        jp: "言語設定",
        cn: "语言设置",
        kr: "언어 설정",
        tr: "Dil Ayarları",
    },
    vrchat_settings: {
        en: "VRChat Settings",
        jp: "VRChat 設定",
        cn: "VRChat 设置",
        kr: "VRChat 설정",
        tr: "VRChat Ayarları",
    },
    omit_questionmark: {
        en: "[Japanese] Omit the trailing question mark",
        jp: "[日本語] 末尾の疑問符を省略",
        cn: "[日语] 省略末尾的问号",
        kr: "[일본어] 물음표를 생략",
        tr: "[Japonca] Son soru işaretini atla",
    },
    translation_first: {
        en: "Show the translation before the original text",
        jp: "元のテキストの前に翻訳を表示",
        cn: "在原始文本之前显示翻译",
        kr: "원본 텍스트 앞에 번역 표시",
        tr: "Orijinal metinden önce çeviriyi göster",
    },
    send_typing_while_talking: {
        en: "Send typing status while talking",
        jp: "会話中に入力ステータスを送信する",
        cn: '正在说话时发送"正在输入"的状态',
        kr: "말하는 동안 입력 상태 보내기",
        tr: "Konuşurken yazma durumu gönder",
    },
    chatbox_update_speed: {
        en: "Chatbox update speed",
        jp: "チャットボックス更新速度",
        cn: "聊天框更新速度",
        kr: "채팅창 업데이트 속도",
        tr: "Sohbet kutusu güncelleme hızı",
    },
    slow: { en: "Slow", jp: "遅い", cn: "慢", kr: "느림", tr: "Yavaş" },
    medium: { en: "Medium", jp: "中", cn: "中", kr: "중간", tr: "Orta" },
    fast: { en: "Fast", jp: "速い", cn: "快", kr: "빠름", tr: "Hızlı" },
    osc_address: {
        en: "OSC Address",
        jp: "OSC アドレス",
        cn: "OSC 地址",
        kr: "OSC 주소",
        tr: "OSC Adresi",
    },
    osc_port: {
        en: "OSC Port",
        jp: "OSC ポート",
        cn: "OSC 端口",
        kr: "OSC 포트",
        tr: "OSC Portu",
    },
    disable_kikitan_when_muted: {
        en: "Disable Kikitan when muted in game",
        jp: "ゲーム内でミュートされているときに Kikitan を無効にする",
        cn: "在游戏中被静音时禁用 Kikitan",
        kr: "게임 내에서 음소거 상태일 때 Kikitan 비활성화",
        tr: "Oyunda susturulduğunda Kikitan'ı devre dışı bırak",
    },
    watch_tutorial: {
        en: "Make sure to watch the tutorial before proceeding!",
        jp: "続行する前にチュートリアルを必ず見てください！",
        cn: "在继续之前，请务必观看教程！",
        kr: "계속하기 전에 튜토리얼을 꼭 시청하세요!",
        tr: "Devam etmeden önce eğitici videoyu izlediğinizden emin olun!",
    },
    changelogs: {
        en: "Changelogs",
        jp: "変更履歴",
        cn: "更新日志",
        kr: "변경 사항",
        tr: "Değişiklikler",
    },
    english_gender_text: {
        en: "When translating to English, change the pronoun. (Ex. He is a doctor/She is a doctor). Useful for languages with gender neutral structure.",
        jp: "変更履歴",
        cn: "翻译成英语时，请更改代词。（例如：他是医生/她是医生。）这对于性别中立结构的语言很有用。",
        kr: "영어로 번역할 때, 대명사를 변경하세요. (예: 그는 의사입니다/그녀는 의사입니다.) 성 중립적 구조를 가진 언어에 유용합니다",
        tr: 'İngilizceye çevirirken, zamiri değiştirin. (Ör. O bir doktordur. "O" burada kız veya erkek olabilir) Cinsiyet nötr yapıya sahip diller için faydalıdır.',
    },
    gender: {
        en: "Gender",
        jp: "性別",
        cn: "性别",
        kr: "성별",
        tr: "Cinsiyet",
    },
    updating: {
        en: "Updating...",
        jp: "更新中...",
        cn: "更新中...",
        kr: "업데이트 중...",
        tr: "Güncelleniyor...",
    },
    waiting_for_mic_access: {
        en: "Waiting for microphone access...",
        jp: "マイクアクセスを待っています...",
        cn: "等待麦克风访问...",
        kr: "마이크 액세스 대기 중...",
        tr: "Mikrofon erişimi bekleniyor...",
    },
    start: { en: "Start", jp: "開始", cn: "开始", kr: "시작", tr: "Başlat" },
    stop: { en: "Stop", jp: "停止", cn: "停止", kr: "중지", tr: "Durdur" },
    unable_to_access_google_servers: {
        en: "Unable to access to Google servers. Please make sure your firewall settings are not blocking the requests or if you're located in a country that has Google servers banned (for example China), make sure your VPN is working properly!",
        jp: "Googleサーバーにアクセスできません。ファイアウォール設定がリクエストをブロックしていないか、Googleサーバーが禁止されている国にいる場合（例：中国）、VPNが正常に動作していることを確認してください！",
        cn: "无法访问谷歌服务器。请确保您的防火墙设置未阻止请求，或者如果您位于禁止谷歌服务器的国家（例如中国），请确保您的VPN正常工作！",
        kr: "Google 서버에 액세스할 수 없습니다. 방화벽 설정이 요청을 차단하고 있지 않은지 또는 Google 서버가 금지된 국가에 위치한 경우(예: 중국) VPN이 제대로 작동하는지 확인하세요!",
        tr: "Google sunucularına erişilemiyor. Güvenlik duvarı ayarlarınızın istekleri engellemediğinden veya Google sunucularının yasaklandığı bir ülkede bulunuyorsanız (örneğin Çin), VPN'inizin düzgün çalıştığından emin olun!",
    },
    donation_text: {
        en: "Kikitan is free and will always stay free. However, any support is hugely welcome! Since I am still a student, anything I receive helps me live better! So, if you enjoy using Kikitan, considering donating!",
        jp: "Kikitanは無料で、常に無料のままです。ただし、どんなサポートも大歓迎です！私はまだ学生なので、受け取るものは何でも私の生活をより良くするのに役立ちます！ですので、Kikitanを楽しんでいる場合は、寄付を検討してください！",
        cn: "Kikitan 是免费的，将永远保持免费。但是，任何支持都非常受欢迎！由于我仍然是一名学生，我收到的任何东西都有助于我过得更好！因此，如果您喜欢使用Kikitan，请考虑捐赠！",
        kr: "Kikitan은 무료이며 항상 무료로 유지됩니다. 그러나 모든 지원을 환영합니다! 아직 학생이기 때문에 받는 모든 것이 나를 더 나은 삶을 살게 도와줍니다! 그러니 Kikitan을 사용하는 것을 즐기신다면 기부를 고려해보세요!",
        tr: "Kikitan ücretsizdir ve her zaman ücretsiz kalacaktır. Ancak, her türlü desteğe açığım! Hala bir öğrenci olduğum için aldığım her bağış benim daha iyi yaşamama yardımcı olur! Bu yüzden, Kikitan'ı kullanmaktan keyif alıyorsanız, bağış yapmayı düşünün!",
    },
    donate: {
        en: "Donate",
        jp: "寄付",
        cn: "捐赠",
        kr: "기부",
        tr: "Bağış Yap",
    },
    debug_settings: {
        en: "Debug",
        jp: "デバッグ",
        cn: "调试",
        kr: "디버그",
        tr: "Hata Ayıklama",
    },
    open_logs: {
        en: "Open Logs",
        jp: "ログを開く",
        cn: "打开日志",
        kr: "로그 열기",
        tr: "Günlükleri Aç",
    },
    voice_recognition_engine: {
        en: "Voice Recognition Engine",
        jp: "音声認識エンジン",
        cn: "语音识别引擎",
        kr: "음성 인식 엔진",
        tr: "Ses Tanıma Motoru",
    },
    retry: {
        en: "Retry",
        jp: "再試行",
        cn: "重试",
        kr: "다시 시도",
        tr: "Tekrar Dene",
    },
    get_gemini_api_key: {
        en: "Get Gemini API Key",
        jp: "Gemini APIキーを取得",
        cn: "获取Gemini API密钥",
        kr: "Gemini API 키 받기",
        tr: "Gemini API Anahtarı Al",
    },
    auto: {
        en: "Auto (Gemini)",
        jp: "自動 (Gemini)",
        cn: "自动 (Gemini)",
        kr: "자동 (Gemini)",
        tr: "Otomatik (Gemini)",
    },
    gemini_api_key_tutorial: {
        en: "How to get a Gemini API key",
        jp: "Gemini APIキーの取得方法",
        cn: "如何获取Gemini API密钥",
        kr: "Gemini API 키를 얻는 방법",
        tr: "Gemini API anahtarı nasıl alınır",
    },
    translator: {
        en: "Translator",
        jp: "翻訳機",
        cn: "翻译器",
        kr: "번역기",
        tr: "Çevirmen",
    },
    only_send_translation: {
        en: "Do not send the original text to the chatbox",
        jp: "元のテキストをチャットボックスに送信しない",
        cn: "不要将原始文本发送到聊天框",
        kr: "원본 텍스트를 채팅창에 보내지 않음",
        tr: "Orijinal metni sohbet kutusuna gönderme",
    },
    google_gemini_note: {
        en: 'Kikitan uses Google\'s Gemini AI model to recognize both your voice and the others (via Desktop Audio Capture). To utilize it, grab your API key and paste it into the box below. You can press "How to get API key" button to get instructions on how to grab the API key after pressing "Get API Key" button. If you don\'t provide an API key, Kikitan will use WebSpeech API and Google Translate which is less accurate. You can always change your API key later in the settings.',
        jp: "Kikitanは、あなたと他の人（デスクトップ音声キャプチャ経由）の音声を認識するために、GoogleのGemini AIモデルを使用します。これを利用するには、APIキーを取得し、下のボックスに貼り付けてください。「APIキーを取得」ボタンを押した後、キーの取得方法に関する説明を見るには「APIキーの取得方法」ボタンを押してください。APIキーを入力しない場合、Kikitanは精度の低いWebSpeech APIとGoogle翻訳を使用します。APIキーは後からいつでも設定で変更できます。",
        cn: "Kikitan 使用谷歌的 Gemini AI 模型来识别您和他人（通过桌面音频捕获）的声音。要使用此功能，请获取您的 API 密钥并将其粘贴到下方的输入框中。在按下“获取API密钥”按钮后，您可以再按下“如何获取API密钥”按钮来查看获取API密钥的说明。如果您不提供API密钥，Kikitan将使用精度较低的WebSpeech API和谷歌翻译。您随时可以在设置中更改您的API密钥。",
        kr: 'Kikitan은 Google의 Gemini AI 모델을 사용하여 사용자 및 다른 사람의 음성(데스크톱 오디오 캡처를 통해)을 인식합니다. 이 기능을 활용하려면 API 키를 받아 아래 상자에 붙여넣으세요. "API 키 발급" 버튼을 누른 후, API 키를 발급받는 방법에 대한 안내가 필요하면 "API 키 발급 방법" 버튼을 누르시면 됩니다. API 키를 제공하지 않으면 Kikitan은 정확도가 낮은 WebSpeech API와 Google 번역을 사용합니다. API 키는 나중에 언제든지 설정에서 변경할 수 있습니다.',
        tr: 'Kikitan, hem sizin hem de diğerlerinin sesini (Masaüstü Ses Yakalama yoluyla) tanımak için Google\'ın Gemini AI modelini kullanır. Bunu kullanmak için API anahtarınızı alın ve aşağıdaki kutuya yapıştırın. "API Anahtarı Al" düğmesine bastıktan sonra, API anahtarını nasıl alacağınıza dair talimatlar için "API anahtarı nasıl alınır" düğmesine basabilirsiniz. Bir API anahtarı sağlamazsanız, Kikitan daha az doğru olan WebSpeech API ve Google Çeviri\'yi kullanacaktır. API anahtarınızı daha sonra dilediğiniz zaman ayarlardan değiştirebilirsiniz.',
    },
    you_have_empty_apikey: {
        en: "Your API key is empty! Gemini WILL NOT WORK without an API key! If you click next, Gemini will be disabled.",
        jp: "APIキーが空です！APIキーがないとGeminiは動作しません！次へをクリックすると、Geminiは無効になります。",
        cn: "您的API密钥为空！没有API密钥，Gemini将无法工作！如果您点击下一步，Gemini将被禁用。",
        kr: "API 키가 비어 있습니다! API 키 없이는 Gemini가 작동하지 않습니다! 다음을 클릭하면 Gemini가 비활성화됩니다.",
        tr: "API anahtarınız boş! Bir API anahtarı olmadan Gemini ÇALIŞMAYACAKTIR! İleri'ye tıklarsanız, Gemini devre dışı bırakılacaktır.",
    },
    gemini_is_disabled: {
        en: "Gemini is disabled",
        jp: "Gemini は無効です",
        cn: "Gemini 已禁用",
        kr: "젬니가 비활성화되었습니다",
        tr: "Gemini devre dışı",
    },
    settings: {
        en: "Settings",
        jp: "設定",
        cn: "设置",
        kr: "설정",
        tr: "Ayarlar",
    },
    // GEMINI STATUS SECTION
    gemini_not_connected: {
        en: "Gemini is not connected",
        jp: "Gemini は接続されていません",
        cn: "Gemini 未连接",
        kr: "젬니가 연결되지 않았습니다",
        tr: "Gemini bağlı değil",
    },
    connecting_to_gemini: {
        en: "Connecting to Gemini...",
        jp: "Gemini に接続中...",
        cn: "连接到Gemini中...",
        kr: "젬니에 연결 중...",
        tr: "Gemini'ye bağlanıyor...",
    },
    gemini_is_ready: {
        en: "Gemini is ready!",
        jp: "Gemini が準備完了です！",
        cn: "Gemini 准备就绪！",
        kr: "젬니가 준비되었습니다!",
        tr: "Gemini hazır!",
    },
    gemini_status: {
        en: "Gemini Status",
        jp: "Gemini ステータス",
        cn: "Gemini 状态",
        kr: "젬니 상태",
        tr: "Gemini Durumu",
    },
    send: {
        en: "Send",
        jp: "送信",
        cn: "发送",
        kr: "보내기",
        tr: "Gönder",
    },
    message_history: {
        en: "Message History",
        jp: "メッセージ履歴",
        cn: "消息历史",
        kr: "메시지 기록",
        tr: "Mesaj Geçmişi",
    },
    clear_history: {
        en: "Clear History",
        jp: "履歴をクリア",
        cn: "清除历史",
        kr: "기록 지우기",
        tr: "Geçmişi Temizle",
    },
    enable_history: {
        en: "Enable Message History",
        jp: "メッセージ履歴を有効にする",
        cn: "启用消息历史",
        kr: "메시지 기록 활성화",
        tr: "Mesaj Geçmişini Etkinleştir",
    },
    max_history_items: {
        en: "Maximum History Items",
        jp: "最大履歴アイテム数",
        cn: "最大历史记录数",
        kr: "최대 기록 항목 수",
        tr: "Maksimum Geçmiş Öğeleri",
    },
    no_history: {
        en: "No message history",
        jp: "メッセージ履歴がありません",
        cn: "没有消息历史",
        kr: "메시지 기록 없음",
        tr: "Mesaj geçmişi yok",
    },
    data_out: {
        en: "Data Output",
        jp: "データ出力",
        cn: "数据输出",
        kr: "데이터 출력",
        tr: "Veri Çıkışı",
    },
    enable_user_data: {
        en: "Enable User Data",
        jp: "ユーザーデータを有効にする",
        cn: "启用用户数据",
        kr: "사용자 데이터 활성화",
        tr: "Kullanıcı Verilerini Etkinleştir",
    },
    enable_desktop_data: {
        en: "Enable Desktop Transcription and Translation Data",
        jp: "デスクトップ音声認識および翻訳データを有効にする",
        cn: "启用桌面语音识别和翻译数据",
        kr: "데스크톱 음성 인식 및 번역 데이터 활성화",
        tr: "Masaüstü Ses Tanıma ve Çeviri Verilerini Etkinleştir",
    },
    gemini_error: {
        en: "An error occured while trying to connect to Gemini! Your API key might be invalid, you might be rate limited or there is a network issue. Please check your API key through Settings. If you're in a country that has Google services banned (for example China), make sure your VPN is working properly!",
        jp: "Geminiに接続しようとしたときにエラーが発生しました！APIキーが無効である可能性があります。レート制限されているか、ネットワークの問題があります。設定からAPIキーを確認してください。Googleサービスが禁止されている国にいる場合（例：中国）、VPNが正常に動作していることを確認してください！",
        cn: "尝试连接到Gemini时发生错误！您的API密钥可能无效，您可能受到速率限制或存在网络问题。请通过设置检查您的API密钥。如果您位于禁止谷歌服务的国家（例如中国），请确保您的VPN正常工作！",
        kr: "젬니에 연결하는 동안 오류가 발생했습니다! API 키가 잘못되었거나 속도 제한이 걸렸거나 네트워크 문제일 수 있습니다. 설정을 통해 API 키를 확인하세요. Google 서비스가 금지된 국가에 있는 경우(예: 중국) VPN이 제대로 작동하는지 확인하세요!",
        tr: "Gemini'ye bağlanmaya çalışırken bir hata oluştu! API anahtarınız geçersiz olabilir, hız sınırlamasına tabi tutulmuş olabilirsiniz veya bir ağ sorunu olabilir. Lütfen Ayarlar üzerinden API anahtarınızı kontrol edin. Google hizmetlerinin yasaklandığı bir ülkedeyseniz (örneğin Çin), VPN'inizin düzgün çalıştığından emin olun!",
    },
    legacy_capture: {
        en: "Legacy Capture (WebSpeech)",
        jp: "レガシーキャプチャ (WebSpeech)",
        cn: "传统捕获（WebSpeech）",
        kr: "레거시 캡처 (WebSpeech)",
        tr: "Eski Yakalama (WebSpeech)",
    },
    gemini_capture: {
        en: "Gemini Capture (Experimental)",
        jp: "Gemini キャプチャ (実験的)",
        cn: "Gemini 捕获 (实验性)",
        kr: "젬니 캡처 (실험적)",
        tr: "Gemini Yakalama (Deneysel)",
    }
};
