export const localization = {
  quickstart_osc: {
    en: "Make sure to enable OSC!",
    jp: "OSCを有効にしてください！",
    cn: "请确认OSC已开启！",
    kr: "OSC를 활성화하세요!",
    tr: "OSC ayarını etkinleştirdiğinizden emin olun!",
  },
  windows_mic_settings: {
    en: "Check your Windows default microphone settings!",
    jp: "Windowsのデフォルトマイクの設定を確認してください！",
    cn: "请检查windows初始麦克风设定！",
    kr: "Windows 기본 마이크 설정을 확인하세요!",
    tr: "Varsayılan mikrofon ayarlarınızı kontrol edin!",
  },
  windows_mic_details: {
    en: "Make sure to check your Windows microphone settings. Your VR headset microphone (or your actual microphone) must be selected. Don't forget to restart Kikitan after changing the default microphone!",
    jp: "Windowsのマイク設定を確認してください。VRヘッドセットのマイク（または実際に使用しているマイク）が選択されている必要があります。マイクを変更した後にキキタンの再起動が必要です。",
    cn: "请确认windows麦克风设定。请选定VR设备的麦克风（或实际正在使用的麦克风）。在更改麦克风后设置请不要忘了重启Kikitan",
    kr: "Windows 마이크 설정을 확인하세요. VR 헤드셋 마이크(또는 실제 마이크)를 선택해야 합니다. 기본 마이크를 변경한 후 Kikitan을 재시작하는 것을 잊지 마세요!",
    tr: "Windows varsayılan mikrofon ayarlarınızı kontrol edin. VR başlık mikrofonunuz (veya gerçek mikrofonunuz) seçili olmalıdır. Varsayılan mikrofonu değiştirdikten sonra Kikitan'ı yeniden başlatmayı unutmayın!",
  },
  announcement: {
    en: "Announcement",
    jp: "お知らせ",
    cn: "公告",
    kr: "공지",
    tr: "Duyuru",
  },
  enable_gemini: {
    en: "Enable Gemini",
    jp: "ジェミニを有効にする",
    cn: "启用Gemini",
    kr: "젬니 활성화",
    tr: "Gemini'yi etkinleştir",
  },
  enable_gemini_transcription: {
    en: "Enable Gemini Transcription",
    jp: "ジェミニ文字起こしを有効にする",
    cn: "启用Gemini转录",
    kr: "젬니 전사 활성화",
    tr: "Gemini Transkripsiyonu Etkinleştir",
  },
  enable_desktop_capture: {
    en: "Enable Desktop Capture (Experimental!)",
    jp: "デスクトップキャプチャを有効にする (実験的！)",
    cn: "启用桌面捕获 (实验性！)",
    kr: "데스크톱 캡처 활성화 (실험적!)",
    tr: "Masaüstü Yakalama'yı Etkinleştir (Deneysel!)",
  },
  open_win_audio: {
    en: "Open Windows Audio Settings",
    jp: "Windowsのオーディオ設定を開く",
    cn: "打开windows音频设置",
    kr: "Windows 오디오 설정 열기",
    tr: "Windows Ses Ayarlarını Aç",
  },
  stt_text: {
    en: "[VR ONLY] How to use SteamVR STT (Speech to Text)",
    jp: "[VRのみ] SteamVR STT (音声からテキストへ) の使用方法",
    cn: "［仅限VR］SteamVR STT(语音输入）的使用方法",
    kr: "[VR 전용] SteamVR STT (음성 인식) 사용 방법",
    tr: "[SADECE VR] SteamVR STT (Sesli Yazma) nasıl kullanılır",
  },
  change_basic_settings: {
    en: "Change basic settings",
    jp: "基本設定を変更する",
    cn: "更改基本设置",
    kr: "기본 설정 변경",
    tr: "Temel ayarları değiştir",
  },
  text: {
    en: "Text",
    jp: "テキスト",
    cn: "文本",
    kr: "텍스트",
    tr: "Metin",
  },
  mode_selection: {
    en: "Mode Selection",
    jp: "モードの選択",
    cn: "模式选择",
    kr: "모드 선택",
    tr: "Mod Seçimi",
  },
  mode_selection_details: {
    en: "You can change the mode from here. Translation sends both what is said and its translation to VRChat. With transcription, only what is said is sent to VRChat.",
    jp: "ここからモードを変更できます。 翻訳では、発言内容とその翻訳の両方が VRChat に送信されます。 文字起こしでは、話した内容のみが VRChat に送信されます。",
    cn: "您可以在这里更换模式。此翻译将会发送输入内容和翻译之后的内容至VRChat。通过转录，只有说出的内容会被输送至VRChat。",
    kr: "여기서 모드를 변경할 수 있습니다. 번역 모드에서는 말한 내용과 번역된 내용이 모두 VRChat에 전송됩니다. 전사 모드에서는 말한 내용만 VRChat에 전송됩니다.",
    tr: "Modu buradan değiştirebilirsiniz. Çeviri, söylenen şeyi ve çevirisini VRChat'e gönderir. Transkripsiyonda sadece söylenen şey VRChat'e gönderilir.",
  },
  thank_you: {
    en: "Thank you for using Kikitan!",
    jp: "Kikitanをご利用いただき、ありがとうございます！",
    cn: "感谢使用Kikitan!",
    kr: "Kikitan을 사용해 주셔서 감사합니다!",
    tr: "Kikitan'ı kullandığın için teşekkür ederim!",
  },
  thank_you_details: {
    en: "Kikitan is an open source project! Any support for this project would be appreciated!",
    jp: "キキタンはオープンソースプロジェクトです！このプロジェクトへのどんな支援も感謝します！",
    cn: "Kikitan 是一个开源项目！感谢所有对此项目的帮助！",
    kr: "Kikitan은 오픈 소스 프로젝트입니다! 이 프로젝트에 대한 지원에 감사드립니다!",
    tr: "Kikitan açık kaynak bir projedir! Projeye yapılan her türlü desteğe minnettarım!",
  },
  next: { en: "Next", jp: "次", cn: "下一页", kr: "다음", tr: "İleri" },
  previous: { en: "Previous", jp: "前", cn: "上一页", kr: "이전", tr: "Geri" },
  open_repo: {
    en: "Open Repository",
    jp: "リポジトリを開く",
    cn: "打开项目库",
    kr: "저장소 열기",
    tr: "Depoyu Aç",
  },
  close_menu: {
    en: "Close Menu",
    jp: "メニューを閉じる",
    cn: "关闭菜单",
    kr: "메뉴 닫기",
    tr: "Menüyü Kapat",
  },
  translation: {
    en: "Translation",
    jp: "翻訳",
    cn: "翻译",
    kr: "번역",
    tr: "Çeviri",
  },
  type_here: {
    en: "Type here...",
    jp: "ここに入力...",
    cn: "在这里输入...",
    kr: "여기에 입력...",
    tr: "Buraya yazın...",
  },
  transcription: {
    en: "Transcription",
    jp: "文字起こし",
    cn: "转录",
    kr: "전사",
    tr: "Transkripsiyon",
  },
  translation_disabled: {
    en: "Translation is disabled. Enable translation from the setting above.",
    jp: "翻訳が無効になっています。上記の設定から翻訳を有効にしてください。",
    cn: "翻译已禁用。请从上面的设置中启用翻译。",
    kr: "번역이 비활성화되었습니다. 위 설정에서 번역을 활성화하세요.",
    tr: "Çeviri devre dışı. Yukarıdaki ayarları kullanarak çeviriyi etkinleştirin.",
  },
  language_settings: {
    en: "Language Settings",
    jp: "言語設定",
    cn: "语言设置",
    kr: "언어 설정",
    tr: "Dil Ayarları",
  },
  vrchat_settings: {
    en: "VRChat Settings",
    jp: "VRChat 設定",
    cn: "VRChat 设置",
    kr: "VRChat 설정",
    tr: "VRChat Ayarları",
  },
  omit_questionmark: {
    en: "[Japanese] Omit the trailing question mark",
    jp: "[日本語] 末尾の疑問符を省略",
    cn: "[日语] 省略末尾的问号",
    kr: "[일본어] 물음표를 생략",
    tr: "[Japonca] Son soru işaretini atla",
  },
  translation_first: {
    en: "Show the translation before the original text",
    jp: "元のテキストの前に翻訳を表示",
    cn: "在原始文本之前显示翻译",
    kr: "원본 텍스트 앞에 번역 표시",
    tr: "Orijinal metinden önce çeviriyi göster",
  },
  send_typing_while_talking: {
    en: "Send typing status while talking",
    jp: "会話中に入力ステータスを送信する",
    cn: "正在说话时发送“正在输入”的状态",
    kr: "말하는 동안 입력 상태 보내기",
    tr: "Konuşurken yazma durumu gönder",
  },
  chatbox_update_speed: {
    en: "Chatbox update speed",
    jp: "チャットボックス更新速度",
    cn: "聊天框更新速度",
    kr: "채팅창 업데이트 속도",
    tr: "Sohbet kutusu güncelleme hızı",
  },
  slow: { en: "Slow", jp: "遅い", cn: "慢", kr: "느림", tr: "Yavaş" },
  medium: { en: "Medium", jp: "中", cn: "中", kr: "중간", tr: "Orta" },
  fast: { en: "Fast", jp: "速い", cn: "快", kr: "빠름", tr: "Hızlı" },
  osc_address: {
    en: "OSC Address",
    jp: "OSC アドレス",
    cn: "OSC 地址",
    kr: "OSC 주소",
    tr: "OSC Adresi",
  },
  osc_port: {
    en: "OSC Port",
    jp: "OSC ポート",
    cn: "OSC 端口",
    kr: "OSC 포트",
    tr: "OSC Portu",
  },
  disable_kikitan_when_muted: {
    en: "Disable Kikitan when muted in game",
    jp: "ゲーム内でミュートされているときに Kikitan を無効にする",
    cn: "在游戏中被静音时禁用 Kikitan",
    kr: "게임 내에서 음소거 상태일 때 Kikitan 비활성화",
    tr: "Oyunda susturulduğunda Kikitan'ı devre dışı bırak"
  },
  changelogs: {
    en: "Changelogs",
    jp: "変更履歴",
    cn: "更新日志",
    kr: "변경 사항",
    tr: "Değişiklikler",
  },
  english_gender_text: {
    en: "When translating to English, change the pronoun. (Ex. He is a doctor/She is a doctor). Useful for languages with gender neutral structure.",
    jp: "変更履歴",
    cn: "翻译成英语时，请更改代词。（例如：他是医生/她是医生。）这对于性别中立结构的语言很有用。",
    kr: "영어로 번역할 때, 대명사를 변경하세요. (예: 그는 의사입니다/그녀는 의사입니다.) 성 중립적 구조를 가진 언어에 유용합니다",
    tr: 'İngilizceye çevirirken, zamiri değiştirin. (Ör. O bir doktordur. "O" burada kız veya erkek olabilir) Cinsiyet nötr yapıya sahip diller için faydalıdır.',
  },
  gender: { en: "Gender", jp: "性別", cn: "性别", kr: "성별", tr: "Cinsiyet" },
  updating: {
    en: "Updating...",
    jp: "更新中...",
    cn: "更新中...",
    kr: "업데이트 중...",
    tr: "Güncelleniyor...",
  },
  waiting_for_mic_access: {
    en: "Waiting for microphone access...",
    jp: "マイクアクセスを待っています...",
    cn: "等待麦克风访问...",
    kr: "마이크 액세스 대기 중...",
    tr: "Mikrofon erişimi bekleniyor...",
  },
  start: { en: "Start", jp: "開始", cn: "开始", kr: "시작", tr: "Başlat" },
  stop: { en: "Stop", jp: "停止", cn: "停止", kr: "중지", tr: "Durdur" },
  unable_to_access_google_servers: {
    en: "Unable to access to Google servers. Please make sure your firewall settings are not blocking the requests or if you're located in a country that has Google servers banned (for example China), make sure your VPN is working properly!",
    jp: "Googleサーバーにアクセスできません。ファイアウォール設定がリクエストをブロックしていないか、Googleサーバーが禁止されている国にいる場合（例：中国）、VPNが正常に動作していることを確認してください！",
    cn: "无法访问谷歌服务器。请确保您的防火墙设置未阻止请求，或者如果您位于禁止谷歌服务器的国家（例如中国），请确保您的VPN正常工作！",
    kr: "Google 서버에 액세스할 수 없습니다. 방화벽 설정이 요청을 차단하고 있지 않은지 또는 Google 서버가 금지된 국가에 위치한 경우(예: 중국) VPN이 제대로 작동하는지 확인하세요!",
    tr: "Google sunucularına erişilemiyor. Güvenlik duvarı ayarlarınızın istekleri engellemediğinden veya Google sunucularının yasaklandığı bir ülkede bulunuyorsanız (örneğin Çin), VPN'inizin düzgün çalıştığından emin olun!",
  },
  donation_text: {
    en: "Kikitan is free and will always stay free. However, any support is hugely welcome! Since I am still a student, anything I receive helps me live better! So, if you enjoy using Kikitan, considering donating!",
    jp: "Kikitanは無料で、常に無料のままです。ただし、どんなサポートも大歓迎です！私はまだ学生なので、受け取るものは何でも私の生活をより良くするのに役立ちます！ですので、Kikitanを楽しんでいる場合は、寄付を検討してください！",
    cn: "Kikitan是免费的，将永远保持免费。但是，任何支持都非常受欢迎！由于我仍然是一名学生，我收到的任何东西都有助于我过得更好！因此，如果您喜欢使用Kikitan，请考虑捐赠！",
    kr: "Kikitan은 무료이며 항상 무료로 유지됩니다. 그러나 모든 지원을 환영합니다! 아직 학생이기 때문에 받는 모든 것이 나를 더 나은 삶을 살게 도와줍니다! 그러니 Kikitan을 사용하는 것을 즐기신다면 기부를 고려해보세요!",
    tr: "Kikitan ücretsizdir ve her zaman ücretsiz kalacaktır. Ancak, her türlü desteğe açığım! Hala bir öğrenci olduğum için aldığım her bağış benim daha iyi yaşamama yardımcı olur! Bu yüzden, Kikitan'ı kullanmaktan keyif alıyorsanız, bağış yapmayı düşünün!",
  },
  donate: { en: "Donate", jp: "寄付", cn: "捐赠", kr: "기부", tr: "Bağış Yap" },
  debug_settings: {
    en: "Debug Settings",
    jp: "デバッグ設定",
    cn: "调试设置",
    kr: "디버그 설정",
    tr: "Hata Ayıklama Ayarları",
  },
  open_logs: {
    en: "Open Logs",
    jp: "ログを開く",
    cn: "打开日志",
    kr: "로그 열기",
    tr: "Günlükleri Aç",
  },
  voice_recognition_engine: {
    en: "Voice Recognition Engine",
    jp: "音声認識エンジン",
    cn: "语音识别引擎",
    kr: "음성 인식 엔진",
    tr: "Ses Tanıma Motoru",
  },
  retry: {
    en: "Retry",
    jp: "再試行",
    cn: "重试",
    kr: "다시 시도",
    tr: "Tekrar Dene",
  },
  get_gemini_api_key: {
    en: "Get Gemini API Key",
    jp: "Gemini APIキーを取得",
    cn: "获取Gemini API密钥",
    kr: "Gemini API 키 받기",
    tr: "Gemini API Anahtarı Al",
  },
  gemini_settings: {
    en: "Gemini Settings",
    jp: "Gemini 設定",
    cn: "Gemini 设置",
    kr: "Gemini 설정",
    tr: "Gemini Ayarları",
  },
  auto: {
    en: "Auto (Gemini)",
    jp: "自動 (Gemini)",
    cn: "自动 (Gemini)",
    kr: "자동 (Gemini)",
    tr: "Otomatik (Gemini)",
  },
  gemini_api_key_tutorial: {
    en: "How to get a Gemini API key",
    jp: "Gemini APIキーの取得方法",
    cn: "如何获取Gemini API密钥",
    kr: "Gemini API 키를 얻는 방법",
    tr: "Gemini API anahtarı nasıl alınır",
  },
  translator: {
    en: "Translator",
    jp: "翻訳機",
    cn: "翻译器",
    kr: "번역기",
    tr: "Çevirmen",
  },
  only_send_translation: {
    en: "Do not send the original text to the chatbox",
    jp: "元のテキストをチャットボックスに送信しない",
    cn: "不要将原始文本发送到聊天框",
    kr: "원본 텍스트를 채팅창에 보내지 않음",
    tr: "Orijinal metni sohbet kutusuna gönderme",
  },
  google_gemini_note: {
    en: "Google's LLM is called Gemini. It's available for translation, and you can even try out the speech-to-text feature (though it might take a little longer sometimes). You'll need a free API key to use it, and getting one is simple – just click the \"How to get Gemini API Key\" button below for a tutorial. Just so you know, this translation tool is still experimental. It uses context to understand and translate better, but if you're using voice input, it might not always be spot-on. Keep that in mind as you use it!",
    jp: "Gemini は Google の大規模言語モデル（LLM）です。翻訳（そしてオプションで音声テキスト変換も可能ですが、時々遅くなることがあります）にご利用いただけます。無料で簡単に入手できる API キーが必要です。以下の「Gemini API キーの取得方法」ボタンをクリックしてチュートリアルをご覧ください。ご注意ください：この機能はまだ実験段階です。文脈に基づいた翻訳と認識により、翻訳ミスを減らすように設計されています。音声テキスト変換機能をご利用の場合、発言された内容が完全に正確に検出されない可能性があります。ご利用にはご注意ください。",
    cn: "Gemini 是 Google 的大型语言模型 (LLM)。你可以用它进行翻译（也可以选择使用语音转文本功能，但有时可能会比较慢）。你需要一个免费且容易获取的 API 密钥，你可以从下面获取（点击“如何获取 Gemini API 密钥”按钮查看教程）。请注意：此功能仍处于实验阶段。它利用上下文驱动的翻译和识别来减少翻译错误。如果你使用的是语音转文本功能，你所说的内容可能不会被完全准确地识别。请谨慎使用！",
    kr: "Gemini는 Google의 대규모 언어 모델(LLM)입니다. 번역 기능(선택적으로 음성-텍스트 변환 기능도 가능하지만, 때때로 속도가 느릴 수 있습니다)을 사용할 수 있습니다. 무료로 쉽게 얻을 수 있는 API 키가 필요하며, 아래에서 얻을 수 있습니다(\"Gemini API 키를 얻는 방법\" 버튼을 클릭하여 안내를 확인하세요). 참고: 이 기능은 아직 실험 단계입니다. 문맥 기반 번역 및 인식을 통해 번역 오류를 줄이도록 설계되었지만, 음성-텍스트 기능을 사용하는 경우 말한 내용이 정확하게 인식되지 않을 수 있습니다. 사용에 주의하세요!",
    tr: "Gemini, Google'ın büyük dil modelidir (LLM). Çeviri (ve isteğe bağlı olarak sesten metne çeviri için de kullanabilirsiniz, ancak zaman zaman yavaşlayabilir). Ücretsiz ve kolayca edinebileceğiniz bir API anahtarına ihtiyacınız olacak, bunu aşağıdan edinebilirsiniz (\"Gemini API Anahtarı Nasıl Alınır\" düğmesine tıklayarak bir öğreticiye ulaşın). Not: Bu özellik hala deneysel aşamadadır. Bağlam odaklı çeviri ve tanıma kullanarak çeviri hatalarını azaltır. Sesten metne özelliğini kullanıyorsanız, söyledikleriniz tam olarak algılanamayabilir. Dikkatli kullanın!",
  },
  gemini_is_disabled: {
    en: "Gemini is disabled",
    jp: "Gemini は無効です",
    cn: "Gemini 已禁用",
    kr: "젬니가 비활성화되었습니다",
    tr: "Gemini devre dışı",
  },
  settings: {
    en: "Settings",
    jp: "設定",
    cn: "设置",
    kr: "설정",
    tr: "Ayarlar",
  },
  // GEMINI STATUS SECTION
  gemini_not_connected: {
    en: "Gemini is not connected",
    jp: "Gemini は接続されていません",
    cn: "Gemini 未连接",
    kr: "젬니가 연결되지 않았습니다",
    tr: "Gemini bağlı değil",
  },
  invalid_gemini_api_key: {
    en: "Invalid Gemini API key. Check your API key and try again.",
    jp: "無効なGemini APIキーです。APIキーを確認してもう一度お試しください。",
    cn: "无效的Gemini API密钥。请检查您的API密钥并重试。",
    kr: "잘못된 젬니 API 키입니다. API 키를 확인하고 다시 시도하세요.",
    tr: "Geçersiz Gemini API anahtarı. API anahtarınızı kontrol edin ve tekrar deneyin.",
  },
  connecting_to_gemini: {
    en: "Connecting to Gemini...",
    jp: "Gemini に接続中...",
    cn: "连接到Gemini中...",
    kr: "젬니에 연결 중...",
    tr: "Gemini'ye bağlanıyor...",
  },
  waiting_for_gemini_setup: {
    en: "Waiting for Gemini setup...",
    jp: "Gemini セットアップを待っています...",
    cn: "等待Gemini设置...",
    kr: "젬니 설정 대기 중...",
    tr: "Gemini kurulumu bekleniyor...",
  },
  gemini_is_ready: {
    en: "Gemini is ready!",
    jp: "Gemini が準備完了です！",
    cn: "Gemini 准备就绪！",
    kr: "젬니가 준비되었습니다!",
    tr: "Gemini hazır!",
  },
  gemini_rate_limit: {
    en: "Gemini rate limit exceeded. Falling back to Google Translate for now",
    jp: "Geminiのレート制限を超過しました。現在はGoogle翻訳にフォールバックします",
    cn: "Gemini速率限制已超过。暂时回退到Google翻译",
    kr: "젬니 요금 한도 초과. 현재는 Google 번역으로 대체됩니다",
    tr: "Gemini hız sınırı aşıldı. Şimdilik Google Çeviri'ye geri dönülüyor"
  },
  send: {
    en: "Send",
    jp: "送信",
    cn: "发送",
    kr: "보내기",
    tr: "Gönder"
  }
};
