namespace KikitanTranslator.Utility
{
    public static class Languages
    {
        public static IReadOnlyDictionary<string, string> SourceLanguages { get; } = new Dictionary<string, string>
        {
            { "en", Resources.LanguageResources.languages.lang_en },
            { "ja", Resources.LanguageResources.languages.lang_ja },
            { "ar", Resources.LanguageResources.languages.lang_ar },
            { "zh", Resources.LanguageResources.languages.lang_zh },
            { "cs", Resources.LanguageResources.languages.lang_cs },
            { "nl", Resources.LanguageResources.languages.lang_nl },
            { "fi", Resources.LanguageResources.languages.lang_fi },
            { "fr", Resources.LanguageResources.languages.lang_fr },
            { "de", Resources.LanguageResources.languages.lang_de },
            { "hu", Resources.LanguageResources.languages.lang_hu },
            { "id", Resources.LanguageResources.languages.lang_id },
            { "it", Resources.LanguageResources.languages.lang_it },
            { "ko", Resources.LanguageResources.languages.lang_ko },
            { "no", Resources.LanguageResources.languages.lang_no },
            { "pl", Resources.LanguageResources.languages.lang_pl },
            { "pt", Resources.LanguageResources.languages.lang_pt },
            { "ro", Resources.LanguageResources.languages.lang_ro },
            { "ru", Resources.LanguageResources.languages.lang_ru },
            { "sv", Resources.LanguageResources.languages.lang_sv },
            { "tr", Resources.LanguageResources.languages.lang_tr }
        };
        
        public static IReadOnlyDictionary<string, string> TargetLanguages { get; } = new Dictionary<string, string>
        {
            { "en", Resources.LanguageResources.languages.lang_en },
            { "ja", Resources.LanguageResources.languages.lang_ja },
            { "ar", Resources.LanguageResources.languages.lang_ar },
            { "hy", Resources.LanguageResources.languages.lang_hy },
            { "bn", Resources.LanguageResources.languages.lang_bn },
            { "bg", Resources.LanguageResources.languages.lang_bg },
            { "ca", Resources.LanguageResources.languages.lang_ca },
            { "zh", Resources.LanguageResources.languages.lang_zh },
            { "hr", Resources.LanguageResources.languages.lang_hr },
            { "cs", Resources.LanguageResources.languages.lang_cs },
            { "da", Resources.LanguageResources.languages.lang_da },
            { "nl", Resources.LanguageResources.languages.lang_nl },
            { "et", Resources.LanguageResources.languages.lang_et },
            { "fi", Resources.LanguageResources.languages.lang_fi },
            { "fr", Resources.LanguageResources.languages.lang_fr },
            { "de", Resources.LanguageResources.languages.lang_de },
            { "el", Resources.LanguageResources.languages.lang_el },
            { "gu", Resources.LanguageResources.languages.lang_gu },
            { "hi", Resources.LanguageResources.languages.lang_hi },
            { "hu", Resources.LanguageResources.languages.lang_hu },
            { "is", Resources.LanguageResources.languages.lang_is },
            { "id", Resources.LanguageResources.languages.lang_id },
            { "it", Resources.LanguageResources.languages.lang_it },
            { "kk", Resources.LanguageResources.languages.lang_kk },
            { "km", Resources.LanguageResources.languages.lang_km },
            { "ko", Resources.LanguageResources.languages.lang_ko },
            { "lo", Resources.LanguageResources.languages.lang_lo },
            { "lv", Resources.LanguageResources.languages.lang_lv },
            { "lt", Resources.LanguageResources.languages.lang_lt },
            { "mk", Resources.LanguageResources.languages.lang_mk },
            { "mr", Resources.LanguageResources.languages.lang_mr },
            { "mn", Resources.LanguageResources.languages.lang_mn },
            { "ne", Resources.LanguageResources.languages.lang_ne },
            { "no", Resources.LanguageResources.languages.lang_no },
            { "or", Resources.LanguageResources.languages.lang_or },
            { "pa", Resources.LanguageResources.languages.lang_pa },
            { "fa", Resources.LanguageResources.languages.lang_fa },
            { "pl", Resources.LanguageResources.languages.lang_pl },
            { "pt", Resources.LanguageResources.languages.lang_pt },
            { "ro", Resources.LanguageResources.languages.lang_ro },
            { "ru", Resources.LanguageResources.languages.lang_ru },
            { "si", Resources.LanguageResources.languages.lang_si },
            { "sk", Resources.LanguageResources.languages.lang_sk },
            { "sl", Resources.LanguageResources.languages.lang_sl },
            { "es", Resources.LanguageResources.languages.lang_es },
            { "sv", Resources.LanguageResources.languages.lang_sv },
            { "ta", Resources.LanguageResources.languages.lang_ta },
            { "te", Resources.LanguageResources.languages.lang_te },
            { "th", Resources.LanguageResources.languages.lang_th },
            { "tr", Resources.LanguageResources.languages.lang_tr },
            { "uk", Resources.LanguageResources.languages.lang_uk },
            { "ur", Resources.LanguageResources.languages.lang_ur },
            { "uz", Resources.LanguageResources.languages.lang_uz },
            { "vi", Resources.LanguageResources.languages.lang_vi }
        };
    }
}