//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikitanTranslator.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KikitanTranslator.Resources.languages", typeof(languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string lang_ar {
            get {
                return ResourceManager.GetString("lang_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string lang_bg {
            get {
                return ResourceManager.GetString("lang_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string lang_bn {
            get {
                return ResourceManager.GetString("lang_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string lang_ca {
            get {
                return ResourceManager.GetString("lang_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string lang_cs {
            get {
                return ResourceManager.GetString("lang_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string lang_da {
            get {
                return ResourceManager.GetString("lang_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string lang_el {
            get {
                return ResourceManager.GetString("lang_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string lang_et {
            get {
                return ResourceManager.GetString("lang_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string lang_fa {
            get {
                return ResourceManager.GetString("lang_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string lang_fi {
            get {
                return ResourceManager.GetString("lang_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string lang_gu {
            get {
                return ResourceManager.GetString("lang_gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string lang_hi {
            get {
                return ResourceManager.GetString("lang_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string lang_hr {
            get {
                return ResourceManager.GetString("lang_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string lang_hu {
            get {
                return ResourceManager.GetString("lang_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string lang_hy {
            get {
                return ResourceManager.GetString("lang_hy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string lang_id {
            get {
                return ResourceManager.GetString("lang_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string lang_is {
            get {
                return ResourceManager.GetString("lang_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh.
        /// </summary>
        public static string lang_kk {
            get {
                return ResourceManager.GetString("lang_kk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string lang_km {
            get {
                return ResourceManager.GetString("lang_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string lang_lo {
            get {
                return ResourceManager.GetString("lang_lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string lang_lt {
            get {
                return ResourceManager.GetString("lang_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string lang_lv {
            get {
                return ResourceManager.GetString("lang_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string lang_mk {
            get {
                return ResourceManager.GetString("lang_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string lang_mn {
            get {
                return ResourceManager.GetString("lang_mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathi.
        /// </summary>
        public static string lang_mr {
            get {
                return ResourceManager.GetString("lang_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepali.
        /// </summary>
        public static string lang_ne {
            get {
                return ResourceManager.GetString("lang_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string lang_nl {
            get {
                return ResourceManager.GetString("lang_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string lang_no {
            get {
                return ResourceManager.GetString("lang_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odia.
        /// </summary>
        public static string lang_or {
            get {
                return ResourceManager.GetString("lang_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjabi.
        /// </summary>
        public static string lang_pa {
            get {
                return ResourceManager.GetString("lang_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string lang_pl {
            get {
                return ResourceManager.GetString("lang_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string lang_pt {
            get {
                return ResourceManager.GetString("lang_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string lang_ro {
            get {
                return ResourceManager.GetString("lang_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala.
        /// </summary>
        public static string lang_si {
            get {
                return ResourceManager.GetString("lang_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string lang_sk {
            get {
                return ResourceManager.GetString("lang_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string lang_sl {
            get {
                return ResourceManager.GetString("lang_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string lang_sv {
            get {
                return ResourceManager.GetString("lang_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string lang_ta {
            get {
                return ResourceManager.GetString("lang_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string lang_te {
            get {
                return ResourceManager.GetString("lang_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string lang_th {
            get {
                return ResourceManager.GetString("lang_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string lang_tr {
            get {
                return ResourceManager.GetString("lang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string lang_uk {
            get {
                return ResourceManager.GetString("lang_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string lang_ur {
            get {
                return ResourceManager.GetString("lang_ur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string lang_uz {
            get {
                return ResourceManager.GetString("lang_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string lang_vi {
            get {
                return ResourceManager.GetString("lang_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
    }
}
