//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikitanTranslator.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class languages_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public languages_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KikitanTranslator.Resources.LanguageResources.languages.ko", typeof(languages_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아랍어.
        /// </summary>
        public static string lang_ar {
            get {
                return ResourceManager.GetString("lang_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불가리아어.
        /// </summary>
        public static string lang_bg {
            get {
                return ResourceManager.GetString("lang_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 벵골어.
        /// </summary>
        public static string lang_bn {
            get {
                return ResourceManager.GetString("lang_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카탈루냐어.
        /// </summary>
        public static string lang_ca {
            get {
                return ResourceManager.GetString("lang_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 체코어.
        /// </summary>
        public static string lang_cs {
            get {
                return ResourceManager.GetString("lang_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 덴마크어.
        /// </summary>
        public static string lang_da {
            get {
                return ResourceManager.GetString("lang_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 독일어.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 그리스어.
        /// </summary>
        public static string lang_el {
            get {
                return ResourceManager.GetString("lang_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 영어.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스페인어.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에스토니아어.
        /// </summary>
        public static string lang_et {
            get {
                return ResourceManager.GetString("lang_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 페르시아어.
        /// </summary>
        public static string lang_fa {
            get {
                return ResourceManager.GetString("lang_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 핀란드어.
        /// </summary>
        public static string lang_fi {
            get {
                return ResourceManager.GetString("lang_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프랑스어.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 구자라트어.
        /// </summary>
        public static string lang_gu {
            get {
                return ResourceManager.GetString("lang_gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 힌디어.
        /// </summary>
        public static string lang_hi {
            get {
                return ResourceManager.GetString("lang_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크로아티아어.
        /// </summary>
        public static string lang_hr {
            get {
                return ResourceManager.GetString("lang_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 헝가리어.
        /// </summary>
        public static string lang_hu {
            get {
                return ResourceManager.GetString("lang_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아르메니아어.
        /// </summary>
        public static string lang_hy {
            get {
                return ResourceManager.GetString("lang_hy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 인도네시아어.
        /// </summary>
        public static string lang_id {
            get {
                return ResourceManager.GetString("lang_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이슬란드어.
        /// </summary>
        public static string lang_is {
            get {
                return ResourceManager.GetString("lang_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이탈리아어.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일본어.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 카자흐어.
        /// </summary>
        public static string lang_kk {
            get {
                return ResourceManager.GetString("lang_kk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 크메르어.
        /// </summary>
        public static string lang_km {
            get {
                return ResourceManager.GetString("lang_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 라오어.
        /// </summary>
        public static string lang_lo {
            get {
                return ResourceManager.GetString("lang_lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리투아니아어.
        /// </summary>
        public static string lang_lt {
            get {
                return ResourceManager.GetString("lang_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 라트비아어.
        /// </summary>
        public static string lang_lv {
            get {
                return ResourceManager.GetString("lang_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마케도니아어.
        /// </summary>
        public static string lang_mk {
            get {
                return ResourceManager.GetString("lang_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 몽골어.
        /// </summary>
        public static string lang_mn {
            get {
                return ResourceManager.GetString("lang_mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마라티어.
        /// </summary>
        public static string lang_mr {
            get {
                return ResourceManager.GetString("lang_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 네팔어.
        /// </summary>
        public static string lang_ne {
            get {
                return ResourceManager.GetString("lang_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 네덜란드어.
        /// </summary>
        public static string lang_nl {
            get {
                return ResourceManager.GetString("lang_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 노르웨이어.
        /// </summary>
        public static string lang_no {
            get {
                return ResourceManager.GetString("lang_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오디아어.
        /// </summary>
        public static string lang_or {
            get {
                return ResourceManager.GetString("lang_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 펀자비어.
        /// </summary>
        public static string lang_pa {
            get {
                return ResourceManager.GetString("lang_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴란드어.
        /// </summary>
        public static string lang_pl {
            get {
                return ResourceManager.GetString("lang_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 포르투갈어.
        /// </summary>
        public static string lang_pt {
            get {
                return ResourceManager.GetString("lang_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 루마니아어.
        /// </summary>
        public static string lang_ro {
            get {
                return ResourceManager.GetString("lang_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 러시아어.
        /// </summary>
        public static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 싱할라어.
        /// </summary>
        public static string lang_si {
            get {
                return ResourceManager.GetString("lang_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 슬로바키아어.
        /// </summary>
        public static string lang_sk {
            get {
                return ResourceManager.GetString("lang_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 슬로베니아어.
        /// </summary>
        public static string lang_sl {
            get {
                return ResourceManager.GetString("lang_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스웨덴어.
        /// </summary>
        public static string lang_sv {
            get {
                return ResourceManager.GetString("lang_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타밀어.
        /// </summary>
        public static string lang_ta {
            get {
                return ResourceManager.GetString("lang_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 텔루구어.
        /// </summary>
        public static string lang_te {
            get {
                return ResourceManager.GetString("lang_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 태국어.
        /// </summary>
        public static string lang_th {
            get {
                return ResourceManager.GetString("lang_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 터키어.
        /// </summary>
        public static string lang_tr {
            get {
                return ResourceManager.GetString("lang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 우크라이나어.
        /// </summary>
        public static string lang_uk {
            get {
                return ResourceManager.GetString("lang_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 우르두어.
        /// </summary>
        public static string lang_ur {
            get {
                return ResourceManager.GetString("lang_ur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 우즈베크어.
        /// </summary>
        public static string lang_uz {
            get {
                return ResourceManager.GetString("lang_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 베트남어.
        /// </summary>
        public static string lang_vi {
            get {
                return ResourceManager.GetString("lang_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 중국어.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
    }
}
