//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikitanTranslator.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class languages_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public languages_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KikitanTranslator.Resources.LanguageResources.languages.zh", typeof(languages_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阿拉伯语.
        /// </summary>
        public static string lang_ar {
            get {
                return ResourceManager.GetString("lang_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保加利亚语.
        /// </summary>
        public static string lang_bg {
            get {
                return ResourceManager.GetString("lang_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 孟加拉语.
        /// </summary>
        public static string lang_bn {
            get {
                return ResourceManager.GetString("lang_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加泰罗尼亚语.
        /// </summary>
        public static string lang_ca {
            get {
                return ResourceManager.GetString("lang_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捷克语.
        /// </summary>
        public static string lang_cs {
            get {
                return ResourceManager.GetString("lang_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丹麦语.
        /// </summary>
        public static string lang_da {
            get {
                return ResourceManager.GetString("lang_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 德语.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 希腊语.
        /// </summary>
        public static string lang_el {
            get {
                return ResourceManager.GetString("lang_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英语.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西班牙语.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱沙尼亚语.
        /// </summary>
        public static string lang_et {
            get {
                return ResourceManager.GetString("lang_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波斯语.
        /// </summary>
        public static string lang_fa {
            get {
                return ResourceManager.GetString("lang_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 芬兰语.
        /// </summary>
        public static string lang_fi {
            get {
                return ResourceManager.GetString("lang_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法语.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 古吉拉特语.
        /// </summary>
        public static string lang_gu {
            get {
                return ResourceManager.GetString("lang_gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印地语.
        /// </summary>
        public static string lang_hi {
            get {
                return ResourceManager.GetString("lang_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 克罗地亚语.
        /// </summary>
        public static string lang_hr {
            get {
                return ResourceManager.GetString("lang_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 匈牙利语.
        /// </summary>
        public static string lang_hu {
            get {
                return ResourceManager.GetString("lang_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亚美尼亚语.
        /// </summary>
        public static string lang_hy {
            get {
                return ResourceManager.GetString("lang_hy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印尼语.
        /// </summary>
        public static string lang_id {
            get {
                return ResourceManager.GetString("lang_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰岛语.
        /// </summary>
        public static string lang_is {
            get {
                return ResourceManager.GetString("lang_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意大利语.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日语.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哈萨克语.
        /// </summary>
        public static string lang_kk {
            get {
                return ResourceManager.GetString("lang_kk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高棉语.
        /// </summary>
        public static string lang_km {
            get {
                return ResourceManager.GetString("lang_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韩语.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 老挝语.
        /// </summary>
        public static string lang_lo {
            get {
                return ResourceManager.GetString("lang_lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立陶宛语.
        /// </summary>
        public static string lang_lt {
            get {
                return ResourceManager.GetString("lang_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拉脱维亚语.
        /// </summary>
        public static string lang_lv {
            get {
                return ResourceManager.GetString("lang_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 马其顿语.
        /// </summary>
        public static string lang_mk {
            get {
                return ResourceManager.GetString("lang_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蒙古语.
        /// </summary>
        public static string lang_mn {
            get {
                return ResourceManager.GetString("lang_mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 马拉地语.
        /// </summary>
        public static string lang_mr {
            get {
                return ResourceManager.GetString("lang_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尼泊尔语.
        /// </summary>
        public static string lang_ne {
            get {
                return ResourceManager.GetString("lang_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 荷兰语.
        /// </summary>
        public static string lang_nl {
            get {
                return ResourceManager.GetString("lang_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挪威语.
        /// </summary>
        public static string lang_no {
            get {
                return ResourceManager.GetString("lang_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奥里亚语.
        /// </summary>
        public static string lang_or {
            get {
                return ResourceManager.GetString("lang_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旁遮普语.
        /// </summary>
        public static string lang_pa {
            get {
                return ResourceManager.GetString("lang_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波兰语.
        /// </summary>
        public static string lang_pl {
            get {
                return ResourceManager.GetString("lang_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 葡萄牙语.
        /// </summary>
        public static string lang_pt {
            get {
                return ResourceManager.GetString("lang_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 罗马尼亚语.
        /// </summary>
        public static string lang_ro {
            get {
                return ResourceManager.GetString("lang_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 俄语.
        /// </summary>
        public static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 僧伽罗语.
        /// </summary>
        public static string lang_si {
            get {
                return ResourceManager.GetString("lang_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斯洛伐克语.
        /// </summary>
        public static string lang_sk {
            get {
                return ResourceManager.GetString("lang_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斯洛文尼亚语.
        /// </summary>
        public static string lang_sl {
            get {
                return ResourceManager.GetString("lang_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞典语.
        /// </summary>
        public static string lang_sv {
            get {
                return ResourceManager.GetString("lang_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰米尔语.
        /// </summary>
        public static string lang_ta {
            get {
                return ResourceManager.GetString("lang_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰卢固语.
        /// </summary>
        public static string lang_te {
            get {
                return ResourceManager.GetString("lang_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泰语.
        /// </summary>
        public static string lang_th {
            get {
                return ResourceManager.GetString("lang_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 土耳其语.
        /// </summary>
        public static string lang_tr {
            get {
                return ResourceManager.GetString("lang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乌克兰语.
        /// </summary>
        public static string lang_uk {
            get {
                return ResourceManager.GetString("lang_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乌尔都语.
        /// </summary>
        public static string lang_ur {
            get {
                return ResourceManager.GetString("lang_ur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乌兹别克语.
        /// </summary>
        public static string lang_uz {
            get {
                return ResourceManager.GetString("lang_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 越南语.
        /// </summary>
        public static string lang_vi {
            get {
                return ResourceManager.GetString("lang_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
    }
}
