//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikitanTranslator.Resources.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class languages_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public languages_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KikitanTranslator.Resources.LanguageResources.languages.ja", typeof(languages_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アラビア語.
        /// </summary>
        public static string lang_ar {
            get {
                return ResourceManager.GetString("lang_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブルガリア語.
        /// </summary>
        public static string lang_bg {
            get {
                return ResourceManager.GetString("lang_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベンガル語.
        /// </summary>
        public static string lang_bn {
            get {
                return ResourceManager.GetString("lang_bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カタルーニャ語.
        /// </summary>
        public static string lang_ca {
            get {
                return ResourceManager.GetString("lang_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェコ語.
        /// </summary>
        public static string lang_cs {
            get {
                return ResourceManager.GetString("lang_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デンマーク語.
        /// </summary>
        public static string lang_da {
            get {
                return ResourceManager.GetString("lang_da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドイツ語.
        /// </summary>
        public static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ギリシャ語.
        /// </summary>
        public static string lang_el {
            get {
                return ResourceManager.GetString("lang_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英語.
        /// </summary>
        public static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペイン語.
        /// </summary>
        public static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エストニア語.
        /// </summary>
        public static string lang_et {
            get {
                return ResourceManager.GetString("lang_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ペルシャ語.
        /// </summary>
        public static string lang_fa {
            get {
                return ResourceManager.GetString("lang_fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィンランド語.
        /// </summary>
        public static string lang_fi {
            get {
                return ResourceManager.GetString("lang_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フランス語.
        /// </summary>
        public static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グジャラート語.
        /// </summary>
        public static string lang_gu {
            get {
                return ResourceManager.GetString("lang_gu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヒンディー語.
        /// </summary>
        public static string lang_hi {
            get {
                return ResourceManager.GetString("lang_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クロアチア語.
        /// </summary>
        public static string lang_hr {
            get {
                return ResourceManager.GetString("lang_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハンガリー語.
        /// </summary>
        public static string lang_hu {
            get {
                return ResourceManager.GetString("lang_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アルメニア語.
        /// </summary>
        public static string lang_hy {
            get {
                return ResourceManager.GetString("lang_hy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インドネシア語.
        /// </summary>
        public static string lang_id {
            get {
                return ResourceManager.GetString("lang_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイスランド語.
        /// </summary>
        public static string lang_is {
            get {
                return ResourceManager.GetString("lang_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イタリア語.
        /// </summary>
        public static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カザフ語.
        /// </summary>
        public static string lang_kk {
            get {
                return ResourceManager.GetString("lang_kk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クメール語.
        /// </summary>
        public static string lang_km {
            get {
                return ResourceManager.GetString("lang_km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 韓国語.
        /// </summary>
        public static string lang_ko {
            get {
                return ResourceManager.GetString("lang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラオ語.
        /// </summary>
        public static string lang_lo {
            get {
                return ResourceManager.GetString("lang_lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リトアニア語.
        /// </summary>
        public static string lang_lt {
            get {
                return ResourceManager.GetString("lang_lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ラトビア語.
        /// </summary>
        public static string lang_lv {
            get {
                return ResourceManager.GetString("lang_lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マケドニア語.
        /// </summary>
        public static string lang_mk {
            get {
                return ResourceManager.GetString("lang_mk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モンゴル語.
        /// </summary>
        public static string lang_mn {
            get {
                return ResourceManager.GetString("lang_mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マラーティー語.
        /// </summary>
        public static string lang_mr {
            get {
                return ResourceManager.GetString("lang_mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネパール語.
        /// </summary>
        public static string lang_ne {
            get {
                return ResourceManager.GetString("lang_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オランダ語.
        /// </summary>
        public static string lang_nl {
            get {
                return ResourceManager.GetString("lang_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノルウェー語.
        /// </summary>
        public static string lang_no {
            get {
                return ResourceManager.GetString("lang_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オディア語.
        /// </summary>
        public static string lang_or {
            get {
                return ResourceManager.GetString("lang_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パンジャブ語.
        /// </summary>
        public static string lang_pa {
            get {
                return ResourceManager.GetString("lang_pa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポーランド語.
        /// </summary>
        public static string lang_pl {
            get {
                return ResourceManager.GetString("lang_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポルトガル語.
        /// </summary>
        public static string lang_pt {
            get {
                return ResourceManager.GetString("lang_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ルーマニア語.
        /// </summary>
        public static string lang_ro {
            get {
                return ResourceManager.GetString("lang_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロシア語.
        /// </summary>
        public static string lang_ru {
            get {
                return ResourceManager.GetString("lang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シンハラ語.
        /// </summary>
        public static string lang_si {
            get {
                return ResourceManager.GetString("lang_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スロバキア語.
        /// </summary>
        public static string lang_sk {
            get {
                return ResourceManager.GetString("lang_sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スロベニア語.
        /// </summary>
        public static string lang_sl {
            get {
                return ResourceManager.GetString("lang_sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スウェーデン語.
        /// </summary>
        public static string lang_sv {
            get {
                return ResourceManager.GetString("lang_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タミル語.
        /// </summary>
        public static string lang_ta {
            get {
                return ResourceManager.GetString("lang_ta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テルグ語.
        /// </summary>
        public static string lang_te {
            get {
                return ResourceManager.GetString("lang_te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイ語.
        /// </summary>
        public static string lang_th {
            get {
                return ResourceManager.GetString("lang_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トルコ語.
        /// </summary>
        public static string lang_tr {
            get {
                return ResourceManager.GetString("lang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウクライナ語.
        /// </summary>
        public static string lang_uk {
            get {
                return ResourceManager.GetString("lang_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウルドゥー語.
        /// </summary>
        public static string lang_ur {
            get {
                return ResourceManager.GetString("lang_ur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウズベク語.
        /// </summary>
        public static string lang_uz {
            get {
                return ResourceManager.GetString("lang_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ベトナム語.
        /// </summary>
        public static string lang_vi {
            get {
                return ResourceManager.GetString("lang_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国語.
        /// </summary>
        public static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
    }
}
