export const localization = {
    quickstart_osc: {
        en: "Make sure to enable OSC!",
        jp: "OSCを有効にしてください！",
        cn: "请确认OSC已开启！",
        kr: "OSC를 활성화하세요!",
        tr: "OSC ayarını etkinleştirdiğinizden emin olun!",
    },
    how_to_setup_and_use_kikitan: {
        en: "How to setup and use Kikitan",
        jp: "Kikitanの設定と使用方法",
        cn: "如何设置和使用Kikitan",
        kr: "Kikitan 설정 및 사용 방법",
        tr: "Kikitan'ı nasıl kurup kullanabilirsiniz",
    },
    api_key: {
        en: "API Key",
        jp: "APIキー",
        cn: "API密钥",
        kr: "API 키",
        tr: "API Anahtarı",
    },
    default: {
        en: "Default",
        jp: "デフォルト",
        cn: "默认",
        kr: "기본값",
        tr: "Varsayılan",
    },
    use_edge_translate: {
        en: "Use Microsoft Edge Translate",
        jp: "Microsoft Edge Translateを使用する",
        cn: "使用微软Edge翻译",
        kr: "Microsoft Edge 번역 사용",
        tr: "Microsoft Edge Çeviri'yi Kullan",
    },
    windows_mic_settings: {
        en: "Check your Windows default microphone settings!",
        jp: "Windowsのデフォルトマイクの設定を確認してください！",
        cn: "请检查windows初始麦克风设定！",
        kr: "Windows 기본 마이크 설정을 확인하세요!",
        tr: "Varsayılan mikrofon ayarlarınızı kontrol edin!",
    },
    windows_mic_details: {
        en: "Make sure to check your Windows microphone settings. Your VR headset microphone (or your actual microphone) must be selected. Don't forget to restart Kikitan after changing the default microphone!",
        jp: "Windowsのマイク設定を確認してください。VRヘッドセットのマイク（または実際に使用しているマイク）が選択されている必要があります。マイクを変更した後にキキタンの再起動が必要です。",
        cn: "请确认windows麦克风设定。请选定VR设备的麦克风（或实际正在使用的麦克风）。在更改麦克风后设置请不要忘了重启Kikitan",
        kr: "Windows 마이크 설정을 확인하세요. VR 헤드셋 마이크(또는 실제 마이크)를 선택해야 합니다. 기본 마이크를 변경한 후 Kikitan을 재시작하는 것을 잊지 마세요!",
        tr: "Windows varsayılan mikrofon ayarlarınızı kontrol edin. VR başlık mikrofonunuz (veya gerçek mikrofonunuz) seçili olmalıdır. Varsayılan mikrofonu değiştirdikten sonra Kikitan'ı yeniden başlatmayı unutmayın!",
    },
    get_api_key: {
        en: "Get API Key",
        jp: "APIキーを取得する",
        cn: "获取API密钥",
        kr: "API 키 얻기",
        tr: "API Anahtarı Al",
    },
    announcement: {
        en: "Announcement",
        jp: "お知らせ",
        cn: "公告",
        kr: "공지",
        tr: "Duyuru",
    },
    enable_desktop_capture: {
        en: "Enable Desktop Capture",
        jp: "デスクトップキャプチャを有効にする",
        cn: "启用桌面捕获",
        kr: "데스크톱 캡처 활성화",
        tr: "Masaüstü Yakalama'yı Etkinleştir",
    },
    enable_groq_translate: {
        en: "Enable Groq Translate",
        jp: "Groq Translateを有効にする",
        cn: "启用Groq翻译",
        kr: "Groq 번역 활성화",
        tr: "Groq Çeviri'yi Etkinleştir",
    },
    enable_groq_recognition: {
        en: "Enable Groq Recognition",
        jp: "Groq Recognitionを有効にする",
        cn: "启用Groq识别",
        kr: "Groq 인식 활성화",
        tr: "Groq Tanıma'yı Etkinleştir",
    },
    recommended: {
        en: "Recommended",
        jp: "おすすめ",
        cn: "推荐",
        kr: "추천",
        tr: "Tavsiye Edilen",
    },
    legacy_not_recommended: {
        en: "Legacy, not recommended, incompatible with desktop translation",
        jp: "レガシー、推奨されていません、デスクトップ翻訳と互換性がありません",
        cn: "传统，不推荐，与桌面翻译不兼容",
        kr: "레거시, 권장되지 않음, 데스크톱 번역과 호환되지 않음",
        tr: "Eski, önerilmez, masaüstü çeviri ile uyumsuz",
    },
    disable_desktop_capture: {
        en: "Disable Desktop Capture",
        jp: "デスクトップキャプチャを無効にする",
        cn: "禁用桌面捕获",
        kr: "데스크톱 캡처 비활성화",
        tr: "Masaüstü Yakalama'yı Devre Dışı Bırak",
    },
    open_win_audio: {
        en: "Open Windows Audio Settings",
        jp: "Windowsのオーディオ設定を開く",
        cn: "打开windows音频设置",
        kr: "Windows 오디오 설정 열기",
        tr: "Windows Ses Ayarlarını Aç",
    },
    stt_text: {
        en: "[VR ONLY] How to use SteamVR STT (Speech to Text)",
        jp: "[VRのみ] SteamVR STT (音声からテキストへ) の使用方法",
        cn: "［仅限VR］SteamVR STT(语音输入）的使用方法",
        kr: "[VR 전용] SteamVR STT (음성 인식) 사용 방법",
        tr: "[SADECE VR] SteamVR STT (Sesli Yazma) nasıl kullanılır",
    },
    change_basic_settings: {
        en: "Change basic settings",
        jp: "基本設定を変更する",
        cn: "更改基本设置",
        kr: "기본 설정 변경",
        tr: "Temel ayarları değiştir",
    },
    text: {
        en: "Text",
        jp: "テキスト",
        cn: "文本",
        kr: "텍스트",
        tr: "Metin",
    },
    mode_selection: {
        en: "Mode Selection",
        jp: "モードの選択",
        cn: "模式选择",
        kr: "모드 선택",
        tr: "Mod Seçimi",
    },
    mode_selection_details: {
        en: "You can change the mode from here. Translation translates your speech to the specified language while STT only converts your speech to text without translation (can be used if you don't want to speak in game but also don't want to type in the chatbox).",
        jp: "ここからモードを変更できます。翻訳はあなたの音声を指定された言語に翻訳しますが、STTは翻訳せずに音声をテキストに変換するだけです（ゲーム内で話したくないがチャットボックスに入力したくない場合に使用できます）。",
        cn: "您可以从这里更改模式。翻译会将您的语音翻译成指定的语言，而STT只会将您的语音转换为文本而不进行翻译（如果您不想在游戏中说话但也不想在聊天框中输入，可以使用此功能）。",
        kr: "여기에서 모드를 변경할 수 있습니다. 번역은 사용자의 음성을 지정된 언어로 번역하는 반면 STT는 번역 없이 음성을 텍스트로 변환합니다(게임에서 말하고 싶지 않지만 채팅창에 입력하고 싶지 않은 경우 사용할 수 있음).",
        tr: "Buradan modu değiştirebilirsiniz. Çeviri, konuşmanızı belirtilen dile çevirirken, STT yalnızca konuşmanızı çeviri olmadan metne dönüştürür (oyunda konuşmak istemiyorsanız ancak sohbet kutusuna yazmak da istemiyorsanız kullanılabilir).",
    },
    thank_you: {
        en: "Thank you for using Kikitan!",
        jp: "Kikitanをご利用いただき、ありがとうございます！",
        cn: "感谢使用Kikitan!",
        kr: "Kikitan을 사용해 주셔서 감사합니다!",
        tr: "Kikitan'ı kullandığın için teşekkür ederim!",
    },
    thank_you_details: {
        en: "Kikitan will always be free and open source! If you want to support the project, you can do so from Buy Me a Coffee or through Booth.pm!",
        jp: "Kikitanは常に無料でオープンソースです！プロジェクトをサポートしたい場合は、Buy Me a CoffeeまたはBooth.pmからサポートできます！",
        cn: "Kikitan将永远是免费和开源的！如果您想支持该项目，可以通过Buy Me a Coffee或Booth.pm进行支持！",
        kr: "Kikitan은 항상 무료이며 오픈 소스입니다! 프로젝트를 지원하고 싶다면 Buy Me a Coffee 또는 Booth.pm을 통해 지원할 수 있습니다!",
        tr: "Kikitan her zaman ücretsiz ve açık kaynaklı olacaktır! Projeyi desteklemek isterseniz, Buy me a Coffee veya Booth.pm üzerinden destekleyebilirsiniz!",
    },
    next: { en: "Next", jp: "次", cn: "下一页", kr: "다음", tr: "İleri" },
    previous: {
        en: "Previous",
        jp: "前",
        cn: "上一页",
        kr: "이전",
        tr: "Geri",
    },
    open_repo: {
        en: "Open Repository",
        jp: "リポジトリを開く",
        cn: "打开项目库",
        kr: "저장소 열기",
        tr: "Depoyu Aç",
    },
    close_menu: {
        en: "Close Menu",
        jp: "メニューを閉じる",
        cn: "关闭菜单",
        kr: "메뉴 닫기",
        tr: "Menüyü Kapat",
    },
    translation: {
        en: "Translation",
        jp: "翻訳",
        cn: "翻译",
        kr: "번역",
        tr: "Çeviri",
    },
    type_here: {
        en: "Type here...",
        jp: "ここに入力...",
        cn: "在这里输入...",
        kr: "여기에 입력...",
        tr: "Buraya yazın...",
    },
    stt_only: {
        en: "Speech-to-Text (STT) Only",
        jp: "音声からテキストへ (STT) のみ",
        cn: "仅语音转文本 (STT)",
        kr: "음성 인식 전용 (STT)",
        tr: "Sadece Sesli Metin (STT)",
    },
    language_settings: {
        en: "Language Settings",
        jp: "言語設定",
        cn: "语言设置",
        kr: "언어 설정",
        tr: "Dil Ayarları",
    },
    vrchat_settings: {
        en: "VRChat Settings",
        jp: "VRChat 設定",
        cn: "VRChat 设置",
        kr: "VRChat 설정",
        tr: "VRChat Ayarları",
    },
    omit_questionmark: {
        en: "[Japanese] Omit the trailing question mark",
        jp: "[日本語] 末尾の疑問符を省略",
        cn: "[日语] 省略末尾的问号",
        kr: "[일본어] 물음표를 생략",
        tr: "[Japonca] Son soru işaretini atla",
    },
    translation_first: {
        en: "Show the translation before the original text",
        jp: "元のテキストの前に翻訳を表示",
        cn: "在原始文本之前显示翻译",
        kr: "원본 텍스트 앞에 번역 표시",
        tr: "Orijinal metinden önce çeviriyi göster",
    },
    send_typing_while_talking: {
        en: "Send typing status while talking",
        jp: "会話中に入力ステータスを送信する",
        cn: '正在说话时发送"正在输入"的状态',
        kr: "말하는 동안 입력 상태 보내기",
        tr: "Konuşurken yazma durumu gönder",
    },
    chatbox_update_speed: {
        en: "Chatbox update speed",
        jp: "チャットボックス更新速度",
        cn: "聊天框更新速度",
        kr: "채팅창 업데이트 속도",
        tr: "Sohbet kutusu güncelleme hızı",
    },
    translation_service: {
        en: "Translation Service",
        jp: "翻訳サービス",
        cn: "翻译服务",
        kr: "번역 서비스",
        tr: "Çeviri Servisi",
    },
    recognition_service: {
        en: "Speech Recognition Service",
        jp: "音声認識サービス",
        cn: "语音识别服务",
        kr: "음성 인식 서비스",
        tr: "Ses Tanıma Servisi",
    },
    requires_free_api_key: {
        en: "Requires Free API key",
        jp: "無料APIキーが必要",
        cn: "需要免费API密钥",
        kr: "무료 API 키 필요",
        tr: "Ücretsiz API anahtarı gerektirir",
    },
    requires_paid_api_key: {
        en: "Requires Paid API key",
        jp: "有料APIキーが必要",
        cn: "需要付费API密钥",
        kr: "유료 API 키 필요",
        tr: "Ücretli API anahtarı gerektirir",
    },
    free: { en: "Free", jp: "無料", cn: "免费", kr: "무료", tr: "Ücretsiz" },
    paid: { en: "Paid", jp: "有料", cn: "付费", kr: "유료", tr: "Ücretli" },
    slow: { en: "Slow", jp: "遅い", cn: "慢", kr: "느림", tr: "Yavaş" },
    medium: { en: "Medium", jp: "中", cn: "中", kr: "중간", tr: "Orta" },
    fast: { en: "Fast", jp: "速い", cn: "快", kr: "빠름", tr: "Hızlı" },
    osc_address: {
        en: "OSC Address",
        jp: "OSC アドレス",
        cn: "OSC 地址",
        kr: "OSC 주소",
        tr: "OSC Adresi",
    },
    osc_port: {
        en: "OSC Port",
        jp: "OSC ポート",
        cn: "OSC 端口",
        kr: "OSC 포트",
        tr: "OSC Portu",
    },
    disable_kikitan_when_muted: {
        en: "Disable Kikitan when muted in game",
        jp: "ゲーム内でミュートされているときに Kikitan を無効にする",
        cn: "在游戏中被静音时禁用 Kikitan",
        kr: "게임 내에서 음소거 상태일 때 Kikitan 비활성화",
        tr: "Oyunda susturulduğunda Kikitan'ı devre dışı bırak",
    },
    watch_tutorial: {
        en: "Make sure to watch the tutorial before proceeding!",
        jp: "続行する前にチュートリアルを必ず見てください！",
        cn: "在继续之前，请务必观看教程！",
        kr: "계속하기 전에 튜토리얼을 꼭 시청하세요!",
        tr: "Devam etmeden önce eğitici videoyu izlediğinizden emin olun!",
    },
    changelogs: {
        en: "Changelogs",
        jp: "変更履歴",
        cn: "更新日志",
        kr: "변경 사항",
        tr: "Değişiklikler",
    },
    english_gender_text: {
        en: "When translating to English, change the pronoun. (Ex. He is a doctor/She is a doctor). Useful for languages with gender neutral structure.",
        jp: "変更履歴",
        cn: "翻译成英语时，请更改代词。（例如：他是医生/她是医生。）这对于性别中立结构的语言很有用。",
        kr: "영어로 번역할 때, 대명사를 변경하세요. (예: 그는 의사입니다/그녀는 의사입니다.) 성 중립적 구조를 가진 언어에 유용합니다",
        tr: 'İngilizceye çevirirken, zamiri değiştirin. (Ör. O bir doktordur. "O" burada kız veya erkek olabilir) Cinsiyet nötr yapıya sahip diller için faydalıdır.',
    },
    gender: {
        en: "Gender",
        jp: "性別",
        cn: "性别",
        kr: "성별",
        tr: "Cinsiyet",
    },
    updating: {
        en: "Updating...",
        jp: "更新中...",
        cn: "更新中...",
        kr: "업데이트 중...",
        tr: "Güncelleniyor...",
    },
    waiting_for_mic_access: {
        en: "Waiting for microphone access...",
        jp: "マイクアクセスを待っています...",
        cn: "等待麦克风访问...",
        kr: "마이크 액세스 대기 중...",
        tr: "Mikrofon erişimi bekleniyor...",
    },
    start: { en: "Start", jp: "開始", cn: "开始", kr: "시작", tr: "Başlat" },
    stop: { en: "Stop", jp: "停止", cn: "停止", kr: "중지", tr: "Durdur" },
    unable_to_access_google_servers: {
        en: "Unable to access to Google servers. Please make sure your firewall settings are not blocking the requests or if you're located in a country that has Google servers banned (for example China), make sure your VPN is working properly!",
        jp: "Googleサーバーにアクセスできません。ファイアウォール設定がリクエストをブロックしていないか、Googleサーバーが禁止されている国にいる場合（例：中国）、VPNが正常に動作していることを確認してください！",
        cn: "无法访问谷歌服务器。请确保您的防火墙设置未阻止请求，或者如果您位于禁止谷歌服务器的国家（例如中国），请确保您的VPN正常工作！",
        kr: "Google 서버에 액세스할 수 없습니다. 방화벽 설정이 요청을 차단하고 있지 않은지 또는 Google 서버가 금지된 국가에 위치한 경우(예: 중국) VPN이 제대로 작동하는지 확인하세요!",
        tr: "Google sunucularına erişilemiyor. Güvenlik duvarı ayarlarınızın istekleri engellemediğinden veya Google sunucularının yasaklandığı bir ülkede bulunuyorsanız (örneğin Çin), VPN'inizin düzgün çalıştığından emin olun!",
    },
    donation_text: {
        en: "Kikitan is free and will always stay free. However, any support is hugely welcome! Since I am still a student, anything I receive helps me live better! So, if you enjoy using Kikitan, considering donating!",
        jp: "Kikitanは無料で、常に無料のままです。ただし、どんなサポートも大歓迎です！私はまだ学生なので、受け取るものは何でも私の生活をより良くするのに役立ちます！ですので、Kikitanを楽しんでいる場合は、寄付を検討してください！",
        cn: "Kikitan 是免费的，将永远保持免费。但是，任何支持都非常受欢迎！由于我仍然是一名学生，我收到的任何东西都有助于我过得更好！因此，如果您喜欢使用Kikitan，请考虑捐赠！",
        kr: "Kikitan은 무료이며 항상 무료로 유지됩니다. 그러나 모든 지원을 환영합니다! 아직 학생이기 때문에 받는 모든 것이 나를 더 나은 삶을 살게 도와줍니다! 그러니 Kikitan을 사용하는 것을 즐기신다면 기부를 고려해보세요!",
        tr: "Kikitan ücretsizdir ve her zaman ücretsiz kalacaktır. Ancak, her türlü desteğe açığım! Hala bir öğrenci olduğum için aldığım her bağış benim daha iyi yaşamama yardımcı olur! Bu yüzden, Kikitan'ı kullanmaktan keyif alıyorsanız, bağış yapmayı düşünün!",
    },
    advanced_settings: {
        en: "Advanced Settings",
        jp: "高度な設定",
        cn: "高级设置",
        kr: "고급 설정",
        tr: "Gelişmiş Ayarlar",
    },
    open_logs: {
        en: "Open Logs",
        jp: "ログを開く",
        cn: "打开日志",
        kr: "로그 열기",
        tr: "Günlükleri Aç",
    },
    voice_recognition_engine: {
        en: "Voice Recognition Engine",
        jp: "音声認識エンジン",
        cn: "语音识别引擎",
        kr: "음성 인식 엔진",
        tr: "Ses Tanıma Motoru",
    },
    retry: {
        en: "Retry",
        jp: "再試行",
        cn: "重试",
        kr: "다시 시도",
        tr: "Tekrar Dene",
    },
    translator: {
        en: "Translator",
        jp: "翻訳機",
        cn: "翻译器",
        kr: "번역기",
        tr: "Çevirmen",
    },
    only_send_translation: {
        en: "Do not send the original text to the chatbox",
        jp: "元のテキストをチャットボックスに送信しない",
        cn: "不要将原始文本发送到聊天框",
        kr: "원본 텍스트를 채팅창에 보내지 않음",
        tr: "Orijinal metni sohbet kutusuna gönderme",
    },
    settings: {
        en: "Settings",
        jp: "設定",
        cn: "设置",
        kr: "설정",
        tr: "Ayarlar",
    },
    send: {
        en: "Send",
        jp: "送信",
        cn: "发送",
        kr: "보내기",
        tr: "Gönder",
    },
    message_history: {
        en: "Message History",
        jp: "メッセージ履歴",
        cn: "消息历史",
        kr: "메시지 기록",
        tr: "Mesaj Geçmişi",
    },
    clear_history: {
        en: "Clear History",
        jp: "履歴をクリア",
        cn: "清除历史",
        kr: "기록 지우기",
        tr: "Geçmişi Temizle",
    },
    enable_history: {
        en: "Enable Message History",
        jp: "メッセージ履歴を有効にする",
        cn: "启用消息历史",
        kr: "메시지 기록 활성화",
        tr: "Mesaj Geçmişini Etkinleştir",
    },
    max_history_items: {
        en: "Maximum History Items",
        jp: "最大履歴アイテム数",
        cn: "最大历史记录数",
        kr: "최대 기록 항목 수",
        tr: "Maksimum Geçmiş Öğeleri",
    },
    no_history: {
        en: "No message history",
        jp: "メッセージ履歴がありません",
        cn: "没有消息历史",
        kr: "메시지 기록 없음",
        tr: "Mesaj geçmişi yok",
    },
    translator_settings: {
        en: "Translator Settings",
        jp: "翻訳機の設定",
        cn: "翻译器设置",
        kr: "번역기 설정",
        tr: "Çevirmen Ayarları",
    },
    enable_user_data: {
        en: "Send speech recognition and translation data as OSC messages (port 7272)",
        jp: "音声認識と翻訳データをOSCメッセージとして送信する（ポート7272）",
        cn: "将语音识别和翻译数据作为OSC消息发送（端口7272）",
        kr: "음성 인식 및 번역 데이터를 OSC 메시지로 보내기(포트 7272)",
        tr: "Konuşma tanıma ve çeviri verilerini OSC mesajları olarak gönder (port 7272)",
    },
    enable_desktop_data: {
        en: "Send desktop capture transcription and translation data as OSC messages (port 7272)",
        jp: "デスクトップキャプチャの文字起こしと翻訳データをOSCメッセージとして送信する（ポート7272）",
        cn: "将桌面捕获的转录和翻译数据作为OSC消息发送（端口7272）",
        kr: "데스크톱 캡처 전사 및 번역 데이터를 OSC 메시지로 보내기(포트 7272)",
        tr: "Masaüstü yakalama transkripsiyon ve çeviri verilerini OSC mesajları olarak gönder (port 7272)",
    },
    no_api_key_configured_for_groq: {
        en: "No API key configured for Groq. Please go to settings to configure the API key.",
        jp: "GroqのAPIキーが設定されていません。設定に移動してAPIキーを設定してください。",
        cn: "未配置Groq的API密钥。请前往设置配置API密钥。",
        kr: "Groq에 대한 API 키가 구성되지 않았습니다. 설정으로 이동하여 API 키를 구성하세요.",
        tr: "Groq için yapılandırılmış API anahtarı yok. Lütfen API anahtarını yapılandırmak için ayarlara gidin.",
    },
    invalid_api_key_groq: {
        en: "The API key you provided for Groq is invalid. Please check your API key and try again.",
        jp: "Groqに提供したAPIキーが無効です。APIキーを確認して、もう一度お試しください。",
        cn: "您提供的Groq API密钥无效。请检查您的API密钥并重试。",
        kr: "Groq에 대한 API 키가 유효하지 않습니다. API 키를 확인하고 다시 시도하세요.",
        tr: "Groq için sağladığınız API anahtarı geçersiz. Lütfen API anahtarınızı kontrol edin ve tekrar deneyin.",
    },
    limit_reached: {
        en: "You have reached the limit for this service (likely due to free tier limitations). Please switch to a different translator or recognizer or wait until the limit resets.",
        jp: "このサービスの制限に達しました（無料ティアの制限による可能性があります）。別の翻訳機または認識機に切り替えるか、制限がリセットされるまで待ってください。",
        cn: "您已达到此服务的限制（可能是由于免费层级的限制）。请切换到不同的翻译器或识别器，或等待限制重置。",
        kr: "이 서비스의 한도에 도달했습니다 (무료 티어 제한으로 인한 가능성이 큽니다). 다른 번역기 또는 인식기로 전환하거나 한도가 리셋될 때까지 기다리세요.",
        tr: "Bu hizmet için limiti aştınız (ücretsiz katman sınırlamaları nedeniyle olabilir). Lütfen farklı bir çevirmen veya tanımlayıcıya geçin veya limit sıfırlanana kadar bekleyin.",
    },
    reset_usage: {
        en: "Reset Usage",
        jp: "使用量をリセット",
        cn: "重置使用量",
        kr: "사용량 초기화",
        tr: "Kullanımı Sıfırla",
    },
    groq_token_usage: {
        en: "Groq Token Usage",
        jp: "Groqトークン使用量",
        cn: "Groq令牌使用量",
        kr: "Groq 토큰 사용량",
        tr: "Groq Jeton Kullanımı",
    },
    microphone_updated: {
        en: "Your previous microphone is not detected. Switching to your default microphone",
        jp: "前のマイクが検出されません。デフォルトのマイクに切り替えます",
        cn: "未检测到您之前的麦克风。正在切换到您的默认麦克风",
        kr: "이전 마이크가 감지되지 않습니다. 기본 마이크로 전환 중",
        tr: "Önceki mikrofonunuz algılanamadı. Varsayılan mikrofonunuza geçiliyor",
    },
    cannot_use_webspeech_for_desktop_translation: {
        en: "Cannot use WebSpeech for desktop translation! Please change the recognizer service if you want to use it!",
        jp: "WebSpeechをデスクトップ翻訳に使用することはできません！使用したい場合は認識サービスを変更してください！",
        cn: "无法将WebSpeech用于桌面翻译！如果您想使用它，请更改识别器服务！",
        kr: "데스크톱 번역에 WebSpeech를 사용할 수 없습니다! 사용하려면 인식기 서비스를 변경하세요!",
        tr: "WebSpeech'i masaüstü çeviri için kullanamazsınız! Kullanmak istiyorsanız tanımlayıcı hizmetini değiştirin!",
    },
    translation_disabled: {
        en: "Translation is disabled. You can enable it by switching from Speech-to-Text mode to Translation mode.",
        jp: "翻訳は無効になっています。音声認識モードから翻訳モードに切り替えると有効にできます。",
        cn: "翻译已禁用。切换从语音转文字模式到翻译模式即可启用。",
        kr: "번역이 비활성화되었습니다. 음성 인식 모드에서 번역 모드로 전환하면 활성화할 수 있습니다.",
        tr: "Çeviri devre dışı. Konuşmadan Metne modundan Çeviri moduna geçerek etkinleştirebilirsiniz."
    }
};
