export const localization = {
    quickstart_osc: {
        en: "Make sure to enable OSC!",
        jp: "OSCを有効にしてください！",
        cn: "请确保已开启OSC！",
        kr: "OSC를 활성화하세요!",
    },
    how_to_setup_and_use_kikitan: {
        en: "How to setup and use Kikitan",
        jp: "Kikitanの設定と使用方法",
        cn: "如何设置和使用Kikitan",
        kr: "Kikitan 설정 및 사용 방법",
    },
    api_key: {
        en: "API Key",
        jp: "APIキー",
        cn: "API密钥",
        kr: "API 키",
    },
    change_theme: {
        en: "Change Theme",
        jp: "テーマを変更",
        cn: "更改主题",
        kr: "테마 변경"
    },
    change_theme_detail: {
        en: "You can change the theme of the app by pressing the theme button on top right (changes icons when you click on it!)",
        jp: "右上にあるテーマボタンを押すと、アプリのテーマを変更できます（クリックするとアイコンが変わります！）",
        cn: "您可以点击右上角的主题按钮来更改应用主题（点击时图标会随之变化！）",
        kr: "오른쪽 상단의 테마 버튼을 눌러 앱 테마를 변경할 수 있습니다 (클릭하면 아이콘이 변경됩니다!)"
    },
    default: {
        en: "Default",
        jp: "デフォルト",
        cn: "默认",
        kr: "기본값",
    },
    use_edge_translate: {
        en: "Use Microsoft Edge Translate",
        jp: "Microsoft Edge翻訳を使用する",
        cn: "使用Microsoft Edge翻译",
        kr: "Microsoft Edge 번역 사용",
    },
    windows_mic_settings: {
        en: "Check your Windows default microphone settings!",
        jp: "Windowsのデフォルトマイク設定を確認してください！",
        cn: "请检查Windows默认麦克风设置！",
        kr: "Windows 기본 마이크 설정을 확인하세요!",
    },
    windows_mic_details: {
        en: "Make sure to check your Windows microphone settings. Your VR headset microphone (or your actual microphone) must be selected. Don't forget to restart Kikitan after changing the default microphone!",
        jp: "Windowsのマイク設定を確認してください。VRヘッドセットのマイク（または実際に使用しているマイク）が選択されている必要があります。デフォルトのマイクを変更した後はKikitanを再起動してください！",
        cn: "请确认Windows麦克风设置。请选择VR设备的麦克风（或实际正在使用的麦克风）。更改默认麦克风后，请务必重启Kikitan！",
        kr: "Windows 마이크 설정을 확인하세요. VR 헤드셋 마이크(또는 실제 마이크)가 선택되어 있어야 합니다. 기본 마이크를 변경한 후에는 Kikitan을 재시작하는 것을 잊지 마세요!",
    },
    get_api_key: {
        en: "Get API Key",
        jp: "APIキーを取得する",
        cn: "获取API密钥",
        kr: "API 키 받기",
    },
    announcement: {
        en: "Announcement",
        jp: "お知らせ",
        cn: "公告",
        kr: "공지사항",
    },
    enable_desktop_capture: {
        en: "Enable Desktop Capture",
        jp: "デスクトップキャプチャを有効にする",
        cn: "启用桌面捕获",
        kr: "데스크톱 캡처 활성화",
    },
    enable_groq_translate: {
        en: "Enable Groq Translate",
        jp: "Groq翻訳を有効にする",
        cn: "启用Groq翻译",
        kr: "Groq 번역 활성화",
    },
    enable_groq_recognition: {
        en: "Enable Groq Recognition",
        jp: "Groq音声認識を有効にする",
        cn: "启用Groq语音识别",
        kr: "Groq 음성 인식 활성화",
    },
    recommended: {
        en: "Recommended",
        jp: "推奨",
        cn: "推荐",
        kr: "권장",
    },
    legacy_not_recommended: {
        en: "Legacy, not recommended, incompatible with desktop translation",
        jp: "レガシー、非推奨、デスクトップ翻訳と互換性なし",
        cn: "旧版，不推荐，与桌面翻译不兼容",
        kr: "레거시, 권장되지 않음, 데스크톱 번역과 호환되지 않음",
    },
    desktop_capture_enabled: {
        en: "Desktop Capture Enabled",
        jp: "デスクトップキャプチャ有効",
        cn: "桌面捕获已启用",
        kr: "데스크톱 캡처 활성화됨",
    },
    desktop_translation_warning: {
        en: "Desktop translation only works under Windows at the moment!",
        jp: "デスクトップ翻訳は現在、Windowsのみで動作します！",
        cn: "桌面翻译目前仅在Windows下运行！",
        kr: "데스크톱 번역은 현재 Windows에서만 작동합니다!",
    },
    open_win_audio: {
        en: "Open Windows Audio Settings",
        jp: "Windowsのオーディオ設定を開く",
        cn: "打开Windows音频设置",
        kr: "Windows 오디오 설정 열기",
    },
    stt_text: {
        en: "[VR ONLY] How to use SteamVR STT (Speech to Text)",
        jp: "[VRのみ] SteamVR STT（音声テキスト変換）の使用方法",
        cn: "【仅限VR】如何使用SteamVR STT（语音转文字）",
        kr: "[VR 전용] SteamVR STT (음성 인식) 사용 방법",
    },
    change_basic_settings: {
        en: "Change basic settings",
        jp: "基本設定を変更する",
        cn: "更改基本设置",
        kr: "기본 설정 변경",
    },
    text: {
        en: "Text",
        jp: "テキスト",
        cn: "文本",
        kr: "텍스트",
    },
    mode_selection: {
        en: "Mode Selection",
        jp: "モード選択",
        cn: "模式选择",
        kr: "모드 선택",
    },
    mode_selection_details: {
        en: "You can change the mode from here. Translation translates your speech to the specified language while STT only converts your speech to text without translation (can be used if you don't want to speak in game but also don't want to type in the chatbox).",
        jp: "ここからモードを変更できます。翻訳モードでは音声を指定した言語に翻訳し、STTモードでは翻訳なしで音声をテキストに変換します（ゲーム内で声を出したくないがチャットボックスには入力したくない場合に便利です）。",
        cn: "您可以在此处更改模式。翻译模式会将您的语音翻译成指定语言，而STT模式仅将语音转换为文字，不进行翻译（适合不想在游戏中说话、又不想手动输入聊天框的情况）。",
        kr: "여기에서 모드를 변경할 수 있습니다. 번역 모드는 음성을 지정한 언어로 번역하고, STT 모드는 번역 없이 음성을 텍스트로 변환합니다(게임에서 말하고 싶지 않지만 채팅창에 직접 입력하고 싶지 않을 때 유용합니다).",
    },
    desktop_translation: {
        en: "Desktop Translation",
        jp: "デスクトップ翻訳",
        cn: "桌面翻译",
        kr: "데스크톱 번역",
    },
    settings_details: {
        en: "You can access the settings to configure Kikitan by pressing the settings button on top right!",
        jp: "右上の設定ボタンを押すことで、Kikitanの設定にアクセスできます！",
        cn: "通过点击右上角的设置按钮，您可以访问Kikitan的设置！",
        kr: "오른쪽 상단의 설정 버튼을 눌러 Kikitan 설정에 접근할 수 있습니다!",
    },
    disable_kikitan_when_muted_tooltip: {
        en: "Enabling this will make it so that when you're muted in the game, Kikitan will not recognize your voice",
        jp: "これを有効にすると、ゲーム内でミュートされている間、Kikitanがあなたの声を認識しなくなります",
        cn: "启用此选项后，当您在游戏中被静音时，Kikitan将不会识别您的声音",
        kr: "이 기능을 활성화하면 게임에서 음소거 상태일 때 Kikitan이 음성을 인식하지 않습니다",
    },
    do_not_send_original_tooltip: {
        en: "Enabling this will make it so that only the translated text will be sent to the chatbox",
        jp: "これを有効にすると、翻訳されたテキストのみがチャットボックスに送信されます",
        cn: "启用此选项后，只有翻译后的文本会被发送到聊天框",
        kr: "이 기능을 활성화하면 번역된 텍스트만 채팅창으로 전송됩니다",
    },
    desktop_translation_details: {
        en: "You can enable desktop translation from here. When others speak, the app will translate what they're saying and display it. It will appear as a box on the bottom of your main monitor if you're not on VR. If you're on VR, you'll see it appear below the center of your vision (Windows only for now)",
        jp: "ここからデスクトップ翻訳を有効にできます。他の人が話すと、アプリがその内容を翻訳して表示します。VRを使用していない場合は、メインモニターの下部にボックスとして表示されます。VRを使用している場合は、視野の中央下に表示されます（現在はWindowsのみ）",
        cn: "您可以从这里启用桌面翻译。当其他人说话时，应用程序会翻译他们所说的内容并显示出来。如果您不在VR中，它将作为一个框显示在主显示器的底部。如果您在VR中，它将出现在您视野中央的下方（目前仅支持Windows）",
        kr: "여기서 데스크톱 번역을 활성화할 수 있습니다. 다른 사람이 말할 때 앱이 내용을 번역하여 표시합니다. VR을 사용하지 않는 경우 메인 모니터 하단에 박스로 표시됩니다. VR을 사용하는 경우 시야 중앙 아래에 표시됩니다(현재 Windows만 지원)",
    },
    thank_you: {
        en: "Thank you for using Kikitan!",
        jp: "Kikitanをご利用いただき、ありがとうございます！",
        cn: "感谢使用Kikitan！",
        kr: "Kikitan을 사용해 주셔서 감사합니다!",
    },
    thank_you_details: {
        en: "Kikitan will always be free and open source! If you want to support the project, you can do so from Buy Me a Coffee or through Booth.pm!",
        jp: "Kikitanは常に無料かつオープンソースです！プロジェクトを支援したい場合は、Buy Me a CoffeeまたはBooth.pmからご支援いただけます！",
        cn: "Kikitan将永远免费且开源！如果您想支持该项目，可以通过Buy Me a Coffee或Booth.pm进行支持！",
        kr: "Kikitan은 항상 무료이며 오픈 소스입니다! 프로젝트를 지원하고 싶으시다면 Buy Me a Coffee 또는 Booth.pm을 통해 후원하실 수 있습니다!",
    },
    next: { en: "Next", jp: "次へ", cn: "下一页", kr: "다음" },
    previous: {
        en: "Previous",
        jp: "前へ",
        cn: "上一页",
        kr: "이전",
    },
    open_repo: {
        en: "Open Repository",
        jp: "リポジトリを開く",
        cn: "打开代码仓库",
        kr: "저장소 열기",
    },
    close_menu: {
        en: "Close Menu",
        jp: "メニューを閉じる",
        cn: "关闭菜单",
        kr: "메뉴 닫기",
    },
    translation: {
        en: "Translation",
        jp: "翻訳",
        cn: "翻译",
        kr: "번역",
    },
    type_here: {
        en: "Type here...",
        jp: "ここに入力...",
        cn: "在此输入...",
        kr: "여기에 입력...",
    },
    stt_only: {
        en: "Speech-to-Text (STT) Only",
        jp: "音声テキスト変換（STT）のみ",
        cn: "仅语音转文字（STT）",
        kr: "음성 인식 전용 (STT)",
    },
    language_settings: {
        en: "Language Settings",
        jp: "言語設定",
        cn: "语言设置",
        kr: "언어 설정",
    },
    vrchat_settings: {
        en: "VRChat Settings",
        jp: "VRChat設定",
        cn: "VRChat设置",
        kr: "VRChat 설정",
    },
    omit_questionmark: {
        en: "[Japanese] Omit the trailing question mark",
        jp: "【日本語】末尾の疑問符を省略する",
        cn: "【日语】省略末尾问号",
        kr: "[일본어] 끝의 물음표 생략",
    },
    translation_first: {
        en: "Show the translation before the original text",
        jp: "元のテキストより先に翻訳を表示する",
        cn: "在原文之前显示翻译内容",
        kr: "원본 텍스트 앞에 번역 표시",
    },
    send_typing_while_talking: {
        en: "Send typing status while talking",
        jp: "会話中に入力中のステータスを送信する",
        cn: "说话时发送正在输入的状态",
        kr: "말하는 동안 입력 중 상태 전송",
    },
    chatbox_update_speed: {
        en: "Chatbox update speed",
        jp: "チャットボックスの更新速度",
        cn: "聊天框更新速度",
        kr: "채팅창 업데이트 속도",
    },
    translation_service: {
        en: "Translation Service",
        jp: "翻訳サービス",
        cn: "翻译服务",
        kr: "번역 서비스",
    },
    recognition_service: {
        en: "Speech Recognition Service",
        jp: "音声認識サービス",
        cn: "语音识别服务",
        kr: "음성 인식 서비스",
    },
    requires_free_api_key: {
        en: "Requires Free API key",
        jp: "無料APIキーが必要",
        cn: "需要免费API密钥",
        kr: "무료 API 키 필요",
    },
    requires_paid_api_key: {
        en: "Requires Paid API key",
        jp: "有料APIキーが必要",
        cn: "需要付费API密钥",
        kr: "유료 API 키 필요",
    },
    free: { en: "Free", jp: "無料", cn: "免费", kr: "무료" },
    paid: { en: "Paid", jp: "有料", cn: "付费", kr: "유료" },
    slow: { en: "Slow", jp: "低速", cn: "慢", kr: "느림" },
    medium: { en: "Medium", jp: "中速", cn: "中等", kr: "보통" },
    fast: { en: "Fast", jp: "高速", cn: "快", kr: "빠름" },
    osc_address: {
        en: "OSC Address",
        jp: "OSCアドレス",
        cn: "OSC地址",
        kr: "OSC 주소",
    },
    osc_port: {
        en: "OSC Port",
        jp: "OSCポート",
        cn: "OSC端口",
        kr: "OSC 포트",
    },
    disable_kikitan_when_muted: {
        en: "Disable Kikitan when muted in game",
        jp: "ゲーム内でミュート中はKikitanを無効にする",
        cn: "游戏中被静音时禁用Kikitan",
        kr: "게임 내 음소거 시 Kikitan 비활성화",
    },
    watch_tutorial: {
        en: "Make sure to watch the tutorial before proceeding!",
        jp: "続行する前にチュートリアルを必ずご覧ください！",
        cn: "继续操作前请务必观看教程！",
        kr: "계속하기 전에 튜토리얼을 꼭 시청하세요!",
    },
    changelogs: {
        en: "Changelogs",
        jp: "更新履歴",
        cn: "更新日志",
        kr: "변경 사항",
    },
    english_gender_text: {
        en: "When translating to English, change the pronoun. (Ex. He is a doctor/She is a doctor). Useful for languages with gender neutral structure.",
        jp: "英語に翻訳する際に代名詞を変更します（例：He is a doctor / She is a doctor）。性別を区別しない言語構造を持つ言語に便利です。",
        cn: "翻译成英语时更改代词（例：He is a doctor / She is a doctor）。适用于语言结构中性别中立的语言。",
        kr: "영어로 번역할 때 대명사를 변경합니다. (예: He is a doctor / She is a doctor) 성 중립적 구조의 언어에 유용합니다.",
    },
    gender: {
        en: "Gender",
        jp: "性別",
        cn: "性别",
        kr: "성별",
    },
    updating: {
        en: "Updating...",
        jp: "更新中...",
        cn: "更新中...",
        kr: "업데이트 중...",
    },
    waiting_for_mic_access: {
        en: "Waiting for microphone access...",
        jp: "マイクのアクセスを待機中...",
        cn: "等待麦克风权限...",
        kr: "마이크 접근 권한 대기 중...",
    },
    start: { en: "Start", jp: "開始", cn: "开始", kr: "시작" },
    stop: { en: "Stop", jp: "停止", cn: "停止", kr: "중지" },
    unable_to_access_google_servers: {
        en: "Unable to access Google servers. Please make sure your firewall settings are not blocking the requests or if you're located in a country that has Google servers banned (for example China), make sure your VPN is working properly!",
        jp: "Googleサーバーにアクセスできません。ファイアウォールの設定がリクエストをブロックしていないか確認してください。Googleが制限されている国にお住まいの場合（例：中国）は、VPNが正常に動作しているかご確認ください！",
        cn: "无法访问Google服务器。请确保您的防火墙设置未阻止请求。若您位于屏蔽Google的国家（如中国），请确认VPN运行正常！",
        kr: "Google 서버에 접근할 수 없습니다. 방화벽 설정이 요청을 차단하고 있지 않은지 확인하세요. Google이 차단된 국가(예: 중국)에 계신 경우 VPN이 정상 작동 중인지 확인하세요!",
    },
    donation_text: {
        en: "Kikitan is free and will always stay free. However, any support is hugely welcome! Since I am still a student, anything I receive helps me live better! So, if you enjoy using Kikitan, considering donating!",
        jp: "Kikitanは無料で、これからも無料であり続けます。それでも、ご支援はとても励みになります！私はまだ学生ですので、いただいたものは生活の助けになります。Kikitanを楽しんでいただけているなら、ぜひご寄付をご検討ください！",
        cn: "Kikitan是免费的，将来也会一直免费。不过，任何形式的支持都非常欢迎！由于我还是一名学生，收到的每一份支持都能让我生活得更好。如果您喜欢使用Kikitan，欢迎考虑捐赠！",
        kr: "Kikitan은 무료이며 앞으로도 항상 무료입니다. 그래도 어떤 형태의 지원이든 큰 힘이 됩니다! 아직 학생이기 때문에 받는 모든 것이 생활에 도움이 됩니다. Kikitan을 즐겁게 사용하고 계신다면 후원을 고려해 주세요!",
    },
    new_update_available: {
        en: "A new update is available!",
        jp: "新しいアップデートがあります！",
        cn: "有新的更新可用！",
        kr: "새로운 업데이트가 있습니다!",
    },
    update: {
        en: "Update",
        jp: "アップデート",
        cn: "更新",
        kr: "업데이트",
    },
    advanced_settings: {
        en: "Advanced Settings",
        jp: "詳細設定",
        cn: "高级设置",
        kr: "고급 설정",
    },
    open_logs: {
        en: "Open Logs",
        jp: "ログを開く",
        cn: "打开日志",
        kr: "로그 열기",
    },
    voice_recognition_engine: {
        en: "Voice Recognition Engine",
        jp: "音声認識エンジン",
        cn: "语音识别引擎",
        kr: "음성 인식 엔진",
    },
    retry: {
        en: "Retry",
        jp: "再試行",
        cn: "重试",
        kr: "다시 시도",
    },
    translator: {
        en: "Translator",
        jp: "翻訳機",
        cn: "翻译器",
        kr: "번역기",
    },
    only_send_translation: {
        en: "Do not send the original text to the chatbox",
        jp: "元のテキストをチャットボックスに送信しない",
        cn: "不将原始文本发送至聊天框",
        kr: "원본 텍스트를 채팅창에 전송하지 않음",
    },
    settings: {
        en: "Settings",
        jp: "設定",
        cn: "设置",
        kr: "설정",
    },
    send: {
        en: "Send",
        jp: "送信",
        cn: "发送",
        kr: "전송",
    },
    message_history: {
        en: "Message History",
        jp: "メッセージ履歴",
        cn: "消息记录",
        kr: "메시지 기록",
    },
    history: {
        en: "History",
        jp: "履歴",
        cn: "历史",
        kr: "기록",
    },
    clear_history: {
        en: "Clear History",
        jp: "履歴を削除する",
        cn: "清除记录",
        kr: "기록 지우기",
    },
    enable_history: {
        en: "Enable Message History",
        jp: "メッセージ履歴を有効にする",
        cn: "启用消息记录",
        kr: "메시지 기록 활성화",
    },
    max_history_items: {
        en: "Maximum History Items",
        jp: "最大履歴件数",
        cn: "最大记录条数",
        kr: "최대 기록 항목 수",
    },
    no_history: {
        en: "No message history",
        jp: "メッセージ履歴がありません",
        cn: "暂无消息记录",
        kr: "메시지 기록 없음",
    },
    translator_settings: {
        en: "Translator Settings",
        jp: "翻訳機の設定",
        cn: "翻译器设置",
        kr: "번역기 설정",
    },
    enable_user_data: {
        en: "Send speech recognition and translation data as OSC messages (port 7272)",
        jp: "音声認識と翻訳データをOSCメッセージとして送信する（ポート7272）",
        cn: "将语音识别和翻译数据作为OSC消息发送（端口7272）",
        kr: "음성 인식 및 번역 데이터를 OSC 메시지로 전송 (포트 7272)",
    },
    enable_desktop_data: {
        en: "Send desktop capture transcription and translation data as OSC messages (port 7272)",
        jp: "デスクトップキャプチャの文字起こしと翻訳データをOSCメッセージとして送信する（ポート7272）",
        cn: "将桌面捕获的转录和翻译数据作为OSC消息发送（端口7272）",
        kr: "데스크톱 캡처 전사 및 번역 데이터를 OSC 메시지로 전송 (포트 7272)",
    },
    no_api_key_configured_for_groq: {
        en: "No API key configured for Groq. Please go to settings to configure the API key.",
        jp: "GroqのAPIキーが設定されていません。設定画面でAPIキーを設定してください。",
        cn: "未配置Groq的API密钥。请前往设置页面配置API密钥。",
        kr: "Groq API 키가 설정되지 않았습니다. 설정 화면에서 API 키를 구성해 주세요.",
    },
    invalid_api_key_groq: {
        en: "The API key you provided for Groq is invalid. Please check your API key and try again.",
        jp: "Groqに入力されたAPIキーが無効です。APIキーをご確認の上、再度お試しください。",
        cn: "您提供的Groq API密钥无效。请检查API密钥后重试。",
        kr: "입력한 Groq API 키가 유효하지 않습니다. API 키를 확인한 후 다시 시도해 주세요.",
    },
    limit_reached: {
        en: "You have reached the limit for this service (likely due to free tier limitations). Please switch to a different translator or recognizer or wait until the limit resets.",
        jp: "このサービスの利用制限に達しました（無料プランの制限によるものと思われます）。別の翻訳機または認識サービスに切り替えるか、制限がリセットされるまでお待ちください。",
        cn: "您已达到该服务的使用限制（可能由于免费套餐限制）。请切换到其他翻译器或识别器，或等待限制重置。",
        kr: "이 서비스의 사용 한도에 도달했습니다 (무료 플랜 제한으로 인한 가능성이 높습니다). 다른 번역기 또는 인식기로 전환하거나 한도가 초기화될 때까지 기다려 주세요.",
    },
    reset_usage: {
        en: "Reset Usage",
        jp: "使用量をリセットする",
        cn: "重置使用量",
        kr: "사용량 초기화",
    },
    groq_token_usage: {
        en: "Groq Token Usage",
        jp: "Groqトークン使用量",
        cn: "Groq令牌使用量",
        kr: "Groq 토큰 사용량",
    },
    microphone_updated: {
        en: "Your previous microphone is not detected. Switching to your default microphone",
        jp: "以前のマイクが検出されませんでした。デフォルトのマイクに切り替えます",
        cn: "未检测到之前的麦克风，正在切换至默认麦克风",
        kr: "이전 마이크가 감지되지 않아 기본 마이크로 전환합니다",
    },
    cannot_use_webspeech_for_desktop_translation: {
        en: "Cannot use WebSpeech for desktop translation! Please change the recognizer service if you want to use it!",
        jp: "WebSpeechはデスクトップ翻訳に使用できません。使用する場合は認識サービスを変更してください！",
        cn: "WebSpeech无法用于桌面翻译！如需使用，请更改语音识别服务！",
        kr: "WebSpeech는 데스크톱 번역에 사용할 수 없습니다! 사용하려면 음성 인식 서비스를 변경해 주세요!",
    },
    translation_disabled: {
        en: "Translation is disabled. You can enable it by switching from Speech-to-Text mode to Translation mode.",
        jp: "翻訳が無効になっています。音声テキスト変換モードから翻訳モードに切り替えると有効になります。",
        cn: "翻译功能已禁用。您可以将模式从语音转文字切换为翻译模式来启用它。",
        kr: "번역이 비활성화되어 있습니다. 음성 인식 모드에서 번역 모드로 전환하면 활성화할 수 있습니다.",
    },
};