export const langSource = [
    { name: "English (United States)", code: "en-US" },
    { name: "English (United Kingdom)", code: "en-UK" },
    { name: "English (Australia)", code: "en-AU" },
    { name: "English (India)", code: "en-IN" },
    { name: "English (New Zealand)", code: "en-NZ" },
    { name: "English (South Africa)", code: "en-ZA" },
    { name: "日本語 (Japanese)", code: "ja" },
    { name: "العربية (Arabic)", code: "ar" },
    { name: "عربي (Arabic)", code: "ar" },
    { name: "Հայերեն (Armenian)", code: "hy" },
    { name: "বাংলা (Bengali)", code: "bn" },
    { name: "Български (Bulgarian)", code: "bg" },
    { name: "Català (Catalan)", code: "ca" },
    { name: "中文 (Chinese)", code: "zh" },
    { name: "Hrvatski (Croatian)", code: "hr" },
    { name: "Čeština (Czech)", code: "cs" },
    { name: "Dansk (Danish)", code: "da" },
    { name: "Nederlands (Dutch)", code: "nl" },
    { name: "Eesti (Estonian)", code: "et" },
    { name: "Suomi (Finnish)", code: "fi" },
    { name: "Français (French)", code: "fr" },
    { name: "Deutsch (German)", code: "de" },
    { name: "Ελληνικά (Greek)", code: "el" },
    { name: "ગુજરાતી (Gujarati)", code: "gu" },
    { name: "हिन्दी (Hindi)", code: "hi" },
    { name: "Magyar (Hungarian)", code: "hu" },
    { name: "Íslenska (Icelandic)", code: "is" },
    { name: "Bahasa Indonesia (Indonesian)", code: "id" },
    { name: "Italiano (Italian)", code: "it" },
    { name: "Қазақ (Kazakh)", code: "kk" },
    { name: "ភាសាខ្មែរ (Khmer)", code: "km" },
    { name: "한국어 (Korean)", code: "ko" },
    { name: "ລາວ (Lao)", code: "lo" },
    { name: "Latviešu (Latvian)", code: "lv" },
    { name: "Lietuvių (Lithuanian)", code: "lt" },
    { name: "Македонски (Macedonian)", code: "mk" },
    { name: "मराठी (Marathi)", code: "mr" },
    { name: "Монгол (Mongolian)", code: "mn" },
    { name: "नेपाली (Nepali)", code: "ne" },
    { name: "Norsk (Norwegian)", code: "no" },
    { name: "ଓଡ଼ିଆ (Odia)", code: "or" },
    { name: "ਪੰਜਾਬੀ (Punjabi)", code: "pa" },
    { name: "فارسی (Persian)", code: "fa" },
    { name: "Polski (Polish)", code: "pl" },
    { name: "Português (Portuguese)", code: "pt" },
    { name: "Română (Romanian)", code: "ro" },
    { name: "Русский (Russian)", code: "ru" },
    { name: "සිංහල (Sinhala)", code: "si" },
    { name: "Slovenčina (Slovak)", code: "sk" },
    { name: "Slovenščina (Slovenian)", code: "sl" },
    { name: "Español (Spanish)", code: "es" },
    { name: "Svenska (Swedish)", code: "sv" },
    { name: "தமிழ் (Tamil)", code: "ta" },
    { name: "తెలుగు (Telugu)", code: "te" },
    { name: "ไทย (Thai)", code: "th" },
    { name: "Türkçe (Turkish)", code: "tr" },
    { name: "Українська (Ukrainian)", code: "uk" },
    { name: "اردو (Urdu)", code: "ur" },
    { name: "O‘zbek (Uzbek)", code: "uz" },
    { name: "Tiếng Việt (Vietnamese)", code: "vi" },
];

// The reason there are multiple englishes 
// is to have the same length as langSource
export const langTo = [
    { name: "English", code: "en" },
    { name: "English", code: "en" },
    { name: "English", code: "en" },
    { name: "English", code: "en" },
    { name: "English", code: "en" },
    { name: "English", code: "en" },
    { name: "日本語 (Japanese)", code: "ja" },
    { name: "العربية (Arabic)", code: "ar" },
    { name: "عربي (Arabic)", code: "ar" },
    { name: "Հայերեն (Armenian)", code: "hy" },
    { name: "বাংলা (Bengali)", code: "bn" },
    { name: "Български (Bulgarian)", code: "bg" },
    { name: "Català (Catalan)", code: "ca" },
    { name: "中文 (Chinese)", code: "zh" },
    { name: "Hrvatski (Croatian)", code: "hr" },
    { name: "Čeština (Czech)", code: "cs" },
    { name: "Dansk (Danish)", code: "da" },
    { name: "Nederlands (Dutch)", code: "nl" },
    { name: "Eesti (Estonian)", code: "et" },
    { name: "Suomi (Finnish)", code: "fi" },
    { name: "Français (French)", code: "fr" },
    { name: "Deutsch (German)", code: "de" },
    { name: "Ελληνικά (Greek)", code: "el" },
    { name: "ગુજરાતી (Gujarati)", code: "gu" },
    { name: "हिन्दी (Hindi)", code: "hi" },
    { name: "Magyar (Hungarian)", code: "hu" },
    { name: "Íslenska (Icelandic)", code: "is" },
    { name: "Bahasa Indonesia (Indonesian)", code: "id" },
    { name: "Italiano (Italian)", code: "it" },
    { name: "Қазақ (Kazakh)", code: "kk" },
    { name: "ភាសាខ្មែរ (Khmer)", code: "km" },
    { name: "한국어 (Korean)", code: "ko" },
    { name: "ລາວ (Lao)", code: "lo" },
    { name: "Latviešu (Latvian)", code: "lv" },
    { name: "Lietuvių (Lithuanian)", code: "lt" },
    { name: "Македонски (Macedonian)", code: "mk" },
    { name: "मराठी (Marathi)", code: "mr" },
    { name: "Монгол (Mongolian)", code: "mn" },
    { name: "नेपाली (Nepali)", code: "ne" },
    { name: "Norsk (Norwegian)", code: "no" },
    { name: "ଓଡ଼ିଆ (Odia)", code: "or" },
    { name: "ਪੰਜਾਬੀ (Punjabi)", code: "pa" },
    { name: "فارسی (Persian)", code: "fa" },
    { name: "Polski (Polish)", code: "pl" },
    { name: "Português (Portuguese)", code: "pt" },
    { name: "Română (Romanian)", code: "ro" },
    { name: "Русский (Russian)", code: "ru" },
    { name: "සිංහල (Sinhala)", code: "si" },
    { name: "Slovenčina (Slovak)", code: "sk" },
    { name: "Slovenščina (Slovenian)", code: "sl" },
    { name: "Español (Spanish)", code: "es" },
    { name: "Svenska (Swedish)", code: "sv" },
    { name: "தமிழ் (Tamil)", code: "ta" },
    { name: "తెలుగు (Telugu)", code: "te" },
    { name: "ไทย (Thai)", code: "th" },
    { name: "Türkçe (Turkish)", code: "tr" },
    { name: "Українська (Ukrainian)", code: "uk" },
    { name: "اردو (Urdu)", code: "ur" },
    { name: "O‘zbek (Uzbek)", code: "uz" },
    { name: "Tiếng Việt (Vietnamese)", code: "vi" },
]

export function calculateMinWaitTime(text, speed) {
    return (escape(text).length / 3) * speed // in ms
}
