// DISCLAIMER: This file is almost entirely generated by AI as I don't want to deal with any Windows API related thing at all

using System.Diagnostics;
using System.Runtime.InteropServices;
using KikitanTranslator.Utility;
using NAudio.CoreAudioApi;
using NAudio.CoreAudioApi.Interfaces;
using NAudio.Wasapi.CoreAudioApi.Interfaces;
using NAudio.Wave;
using Serilog;

namespace KikitanTranslator.Capture;

public class Loopback : ICapture
{
    private const int SampleRate = 16000;
    private const int VadFrameSamples = 480;
    private const int OutputFrameSamples = VadFrameSamples * 2;
    private const string ProcessLoopbackDevice = "VAD\\Process_Loopback";

    private readonly string _sileroModelPath;
    private readonly object _lifecycleLock = new();
    private CaptureSession? _session;

    public event OnData? OnDataReceived;

    public Loopback(string sileroModelPath) => _sileroModelPath = sileroModelPath;
    public uint GetSampleRate() => SampleRate;

    public bool Start()
    {
        if (!OperatingSystem.IsWindowsVersionAtLeast(10, 0, 20348))
        {
            Log.Error("[LOOP] VRChat process capture requires Windows build 20348 or later");

            return false;
        }

        CaptureSession session;
        lock (_lifecycleLock)
        {
            if (_session != null)
            {
                if (_session.Cancellation.IsCancellationRequested) return false;
                session = _session;
            }
            else
            {
                Process? process = null;
                try
                {
                    process = FindVRChat();
                    if (process == null)
                    {
                        Log.Warning("[LOOP] VRChat.exe is not running in this Windows session");
                        return false;
                    }

                    session = new CaptureSession(process);
                    session.Thread = new Thread(() => Capture(session))
                    {
                        IsBackground = true,
                        Name = "VRChat process audio capture"
                    };

                    _session = session;

                    session.Thread.Start();
                }
                catch (Exception e)
                {
                    _session?.Cancellation.Dispose();
                    _session = null;
                    process?.Dispose();
                    Log.Error(e, "[LOOP] Unable to start VRChat process capture");

                    return false;
                }
            }
        }
        
        Log.Error("[LOOP] Capture started");

        return session.Started.Task.GetAwaiter().GetResult();
    }

    public void Stop()
    {
        CaptureSession? session;
        lock (_lifecycleLock)
        {
            session = _session;
            if (session == null) return;
            session.Cancellation.Cancel();
        }
    }

    public void Pause() => SetPaused(true);
    public void Resume() => SetPaused(false);

    private void SetPaused(bool paused)
    {
        lock (_lifecycleLock)
        {
            if (_session == null || _session.Paused == paused) return;
            _session.Paused = paused;
            Interlocked.Increment(ref _session.FrameGeneration);
        }
    }

    private static Process? FindVRChat()
    {
        using var currentProcess = Process.GetCurrentProcess();
        var windowsSession = currentProcess.SessionId;
        var candidates = Process.GetProcessesByName("VRChat");
        Process? selected = null;
        try
        {
            foreach (var process in candidates)
            {
                try
                {
                    if (process.SessionId == windowsSession && !process.HasExited &&
                        (selected == null || process.Id < selected.Id))
                        selected = process;
                }
                catch (InvalidOperationException)
                {
                }
                catch (System.ComponentModel.Win32Exception)
                {
                }
            }

            return selected;
        }
        finally
        {
            foreach (var process in candidates)
                if (!ReferenceEquals(process, selected))
                    process.Dispose();
        }
    }

    private void Capture(CaptureSession session)
    {
        try
        {
            var token = session.Cancellation.Token;
            using var ready = new AutoResetEvent(false);
            using var client = ActivateProcess(session.Process.Id, token);
            using var vad = new SileroVad(_sileroModelPath);

            token.ThrowIfCancellationRequested();
            if (session.Process.HasExited)
                throw new InvalidOperationException("VRChat exited before capture could start.");

            client.Initialize(AudioClientShareMode.Shared,
                AudioClientStreamFlags.Loopback | AudioClientStreamFlags.EventCallback |
                AudioClientStreamFlags.AutoConvertPcm | AudioClientStreamFlags.SrcDefaultQuality,
                0, 0, new WaveFormat(SampleRate, 16, 1), Guid.Empty);
            client.SetEventHandle(ready.SafeWaitHandle.DangerousGetHandle());
            var capture = client.AudioCaptureClient;

            client.Start();
            try
            {
                token.ThrowIfCancellationRequested();
                Log.Information("[LOOP] Capturing VRChat.exe process tree (PID {ProcessId})", session.Process.Id);
                session.Started.TrySetResult(true);
                ReadPackets(session, capture, ready, vad);
            }
            finally
            {
                client.Stop();
            }
        }
        catch (OperationCanceledException) when (session.Cancellation.IsCancellationRequested)
        {
        }
        catch (Exception e)
        {
            Log.Error(e, "[LOOP] VRChat process capture failed");
        }
        finally
        {
            session.Process.Dispose();
            lock (_lifecycleLock)
            {
                if (ReferenceEquals(_session, session)) _session = null;
                session.Cancellation.Dispose();
            }

            session.Started.TrySetResult(false);
            Log.Information("[LOOP] VRChat process capture has stopped");
        }
    }

    private void ReadPackets(CaptureSession session, AudioCaptureClient capture,
        AutoResetEvent ready, SileroVad vad)
    {
        var token = session.Cancellation.Token;
        WaitHandle[] waits = [token.WaitHandle, ready];
        short[] pcm = [];
        var frame = new float[OutputFrameSamples];
        var frameOffset = 0;
        var generation = Volatile.Read(ref session.FrameGeneration);
        var processCheck = Stopwatch.StartNew();

        while (!token.IsCancellationRequested)
        {
            if (WaitHandle.WaitAny(waits, 250) == 0) break;
            if (processCheck.ElapsedMilliseconds >= 1000)
            {
                if (session.Process.HasExited)
                {
                    Log.Information("[LOOP] VRChat exited; stopping process capture");
                    break;
                }

                processCheck.Restart();
            }

            while (!token.IsCancellationRequested && capture.GetNextPacketSize() > 0)
            {
                var data = capture.GetBuffer(out var sampleCount, out var flags);
                try
                {
                    if (pcm.Length < sampleCount) pcm = new short[sampleCount];
                    if ((flags & AudioClientBufferFlags.Silent) != 0)
                        Array.Clear(pcm, 0, sampleCount);
                    else
                        Marshal.Copy(data, pcm, 0, sampleCount);
                }
                finally
                {
                    capture.ReleaseBuffer(sampleCount);
                }

                var nextGeneration = Volatile.Read(ref session.FrameGeneration);
                if (nextGeneration != generation ||
                    (flags & AudioClientBufferFlags.DataDiscontinuity) != 0)
                {
                    frameOffset = 0;
                    vad.ResetState();
                    generation = nextGeneration;
                }
                
                if (session.Paused) continue;

                for (var i = 0; i < sampleCount; i++)
                {
                    if (token.IsCancellationRequested || session.Paused ||
                        generation != Volatile.Read(ref session.FrameGeneration))
                        break;

                    frame[frameOffset++] = pcm[i] / 32768f;
                    if (frameOffset != frame.Length) continue;
                    
                    var firstSpeech = vad.SpeechDetection(frame.AsSpan(0, VadFrameSamples));
                    var secondSpeech = vad.SpeechDetection(frame.AsSpan(VadFrameSamples, VadFrameSamples));
                    frameOffset = 0;
                    if (!token.IsCancellationRequested && !session.Paused &&
                        generation == Volatile.Read(ref session.FrameGeneration))
                    {
                        try
                        {
                            OnDataReceived?.Invoke(frame, firstSpeech || secondSpeech);
                        }
                        catch (Exception e)
                        {
                            Log.Error(e, "[LOOP] Audio subscriber failed");
                        }
                    }
                    
                    frame = new float[OutputFrameSamples];
                }
            }
        }
    }

    private static AudioClient ActivateProcess(int processId, CancellationToken token)
    {
        var completion = new ActivationCompletion();
        IActivateAudioInterfaceAsyncOperation? operation = null;
        try
        {
            completion.AllocateParameters(processId);
            try
            {
                ActivateAudioInterfaceAsync(ProcessLoopbackDevice, typeof(IAudioClient).GUID,
                    completion.Parameters, completion, out operation);
            }
            catch
            {
                completion.FreeParameters();
                throw;
            }

            object activated;
            try
            {
                activated = completion.Result.Task.WaitAsync(TimeSpan.FromSeconds(10), token)
                    .GetAwaiter().GetResult();
            }
            catch
            {
                _ = completion.Result.Task.ContinueWith(task =>
                {
                    if (task.IsCompletedSuccessfully) Marshal.ReleaseComObject(task.Result);
                    else _ = task.Exception;
                }, CancellationToken.None, TaskContinuationOptions.None, TaskScheduler.Default);
                throw;
            }

            try
            {
                return new AudioClient((IAudioClient)activated);
            }
            catch
            {
                Marshal.ReleaseComObject(activated);
                throw;
            }
        }
        finally
        {
            if (operation != null) Marshal.ReleaseComObject(operation);
            GC.KeepAlive(completion);
        }
    }

    private sealed class CaptureSession(Process process)
    {
        public readonly Process Process = process;
        public readonly CancellationTokenSource Cancellation = new();
        public readonly TaskCompletionSource<bool> Started = new(TaskCreationOptions.RunContinuationsAsynchronously);
        public Thread Thread = null!;
        public volatile bool Paused;
        public int FrameGeneration;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct ProcessActivationParameters
    {
        public uint ActivationType;
        public uint TargetProcessId;
        public uint ProcessLoopbackMode;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct Blob
    {
        public uint Size;
        public IntPtr Data;
    }
    
    [StructLayout(LayoutKind.Sequential)]
    private struct BlobPropVariant
    {
        public ushort VariantType;
        public ushort Reserved1;
        public ushort Reserved2;
        public ushort Reserved3;
        public Blob Blob;
    }

    [ComVisible(true)]
    [Guid("94EA2B94-E9CC-49E0-C0FF-EE64CA8F5B90")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IAgileActivation
    {
    }

    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.None)]
    public sealed class ActivationCompletion : IActivateAudioInterfaceCompletionHandler, IAgileActivation
    {
        internal readonly TaskCompletionSource<object> Result = new(TaskCreationOptions.RunContinuationsAsynchronously);
        internal IntPtr Parameters;
        private IntPtr _activationData;

        internal void AllocateParameters(int processId)
        {
            try
            {
                var activation = new ProcessActivationParameters
                {
                    ActivationType = 1,
                    TargetProcessId = checked((uint)processId),
                    ProcessLoopbackMode = 0
                };
                _activationData = Marshal.AllocHGlobal(Marshal.SizeOf<ProcessActivationParameters>());
                Marshal.StructureToPtr(activation, _activationData, false);
                var variant = new BlobPropVariant
                {
                    VariantType = 65,
                    Blob = new Blob
                    {
                        Size = (uint)Marshal.SizeOf<ProcessActivationParameters>(),
                        Data = _activationData
                    }
                };
                Parameters = Marshal.AllocHGlobal(Marshal.SizeOf<BlobPropVariant>());
                Marshal.StructureToPtr(variant, Parameters, false);
            }
            catch
            {
                FreeParameters();
                throw;
            }
        }

        internal void FreeParameters()
        {
            Marshal.FreeHGlobal(Interlocked.Exchange(ref Parameters, IntPtr.Zero));
            Marshal.FreeHGlobal(Interlocked.Exchange(ref _activationData, IntPtr.Zero));
        }

        public void ActivateCompleted(IActivateAudioInterfaceAsyncOperation operation)
        {
            object? activated = null;
            try
            {
                operation.GetActivateResult(out var result, out activated);
                Marshal.ThrowExceptionForHR(result);
                Result.TrySetResult(activated);
                activated = null;
            }
            catch (Exception e)
            {
                Result.TrySetException(e);
            }
            finally
            {
                if (activated != null) Marshal.ReleaseComObject(activated);
                FreeParameters();
            }
        }
    }

    [DllImport("Mmdevapi.dll", ExactSpelling = true, PreserveSig = false)]
    private static extern void ActivateAudioInterfaceAsync(
        [MarshalAs(UnmanagedType.LPWStr)] string deviceInterfacePath,
        [MarshalAs(UnmanagedType.LPStruct)] Guid interfaceId,
        IntPtr activationParameters,
        IActivateAudioInterfaceCompletionHandler completionHandler,
        out IActivateAudioInterfaceAsyncOperation operation);
}